
### 创建ITSM流程单
POST http://10.11.160.50/itsm-integration/process/on/event
Content-Type: application/json
cookie: blueking_language=zh-cn; KEYCLOAK_LOCALE=zh-CN; bk_token=43spH-QhqQrPeLNncQctIu4S13nHhxKh8zsxrf1j-Idq9sIg9UFFxejuK0C9LFX7; FIT2CLOUD_SESSION_ID=node05f02sddq1cea1sc8xztkswxib310413.node0; JSESSIONID=E26566D93FD3F8A6CD7AD1C1D89DD6A6

{
    "workspaceId": "c2d6106c-3814-4f39-82da-e96028997a84",
    "createTime": "2024-11-15 02:49:27",
    "businessKey": "vm-202411150249-d0816eca",
    "orderType": "DELETE",
    "description": "dwr-1115-02",
    "module": "vm-service",
    "processName": "i18n_vm_application",
    "processEventContext": {
        "task": {
            "taskId": "7901c45e-3449-4d66-a84b-0f190cf5a4da",
            "taskStep": 0,
            "taskName": "提交申请",
            "taskStatus": "COMPLETED",
            "taskAssignee": "lijun.zhang",
            "taskExecutor": "lijun.zhang",
            "taskStartTime": 1731610171897,
            "taskEndTime": 1731610171898,
            "taskActivity": "8a58ee4b-cfdc-42df-a641-caf45557573c",
            "processId": "56f9e6b7-be4b-45f5-8260-833edac88f35",
            "workspaceId": "c2d6106c-3814-4f39-82da-e96028997a84",
            "businessType": "vm-service",
            "businessKey": "vm-202411150249-d0816eca",
            "module": "vm-service",
            "taskAction": "SUBMIT",
            "taskActionContent": "lijun.zhang提交了一个订单",
            "linkBusinessType": "APPROVE",
            "taskChildStep": 0,
            "taskRemarks": "提交申请"
        },
        "process": {
            "processId": "56f9e6b7-be4b-45f5-8260-833edac88f35",
            "processName": "i18n_vm_application",
            "processStatus": "PENDING",
            "processCreator": "lijun.zhang",
            "processStartTime": 1731610171840,
            "deployId": "d9c0b888-0472-416a-8715-b1ad6bf5b5c8",
            "businessKey": "vm-202411150249-d0816eca",
            "businessType": "vm-service",
            "workspaceId": "c2d6106c-3814-4f39-82da-e96028997a84",
            "module": "vm-service"
        },
        "arguments": "SUBMIT"
    },
    "businessDetails": [{
        "detailItems": [{
            "label": "申请数量",
            "hidden": false,
            "text": "1",
            "key": "count",
            "value": "1"
        }, {
            "label": "Place",
            "hidden": false,
            "text": "北京主机房",
            "key": "resource_pool_tag_f53c6ad6-7a49-4e83-a7de-45f447298278",
            "value": "3bbd238a-7001-4166-bbfb-04ffce0d89ae"
        }, {
            "label": "Function",
            "hidden": false,
            "text": "App",
            "key": "resource_pool_tag_f8ec424a-0501-4065-a7bd-f3b5de346bc1",
            "value": "befe8ef1-24e7-424b-92a0-1cc8aff627e5"
        }, {
            "label": "Environments",
            "hidden": false,
            "text": "DEV",
            "key": "resource_pool_tag_a752d43d-c94e-4304-8c5d-8289291e48bb",
            "value": "16d71170-cf9a-47f2-b9be-381a57a59e78"
        }, {
            "label": "资源池分配策略",
            "hidden": false,
            "text": "手动选择",
            "key": "deploy_policy",
            "value": "CUSTOM"
        }, {
            "label": "资源池",
            "hidden": false,
            "text": "CMP-DEV",
            "key": "userSelectResourcePoolIds",
            "value": "805ec456-dd8d-4857-8ff8-a2ce0d92be03"
        }, {
            "label": "资源池",
            "hidden": false,
            "text": "CMP-DEV;",
            "key": "selectResourcePoolIds",
            "value": "[\"805ec456-dd8d-4857-8ff8-a2ce0d92be03\"]"
        }, {
            "label": "IP池",
            "hidden": false,
            "text": "[]",
            "key": "ipPool",
            "value": "[]"
        }, {
            "label": "CPU最大值(核)",
            "hidden": false,
            "text": "128",
            "key": "maxCpuCore",
            "value": "128"
        }, {
            "label": "内存最大值(GB)",
            "hidden": false,
            "text": "256",
            "key": "maxMemory",
            "value": "256"
        }, {
            "label": "申请方式",
            "hidden": false,
            "text": "标准申请",
            "key": "ipVersion",
            "value": "standard"
        }, {
            "label": "申请方式",
            "hidden": false,
            "text": "无",
            "key": "inputGroupBox"
        }, {
            "label": "IP分配策略",
            "hidden": false,
            "text": "回收闲置",
            "key": "delete_reason",
            "value": "auto_from_ippool"
        }, {
            "label": "网络适配器",
            "hidden": false,
            "text": "vlan2503-CMP_TEST(dvSwitch);",
            "key": "network",
            "value": "[\"dvportgroup-15008\"]"
        }, {
            "label": "IP地址",
            "hidden": false,
            "text": "[\"10.11.160.52\"]",
            "key": "ipArray",
            "value": "[\"10.11.160.52\"]"
        }, {
            "label": "实例类型",
            "hidden": false,
            "text": "vm.2C4G [2核4G]",
            "key": "instanceType",
            "value": "14"
        }, {
            "label": "CPU 核数",
            "hidden": false,
            "text": "2",
            "key": "cpuCount",
            "value": "2"
        }, {
            "label": "每个插槽内核数",
            "hidden": false,
            "text": "1",
            "key": "cpuPerSocket",
            "value": "1"
        }, {
            "label": "内存大小",
            "hidden": false,
            "text": "4096",
            "key": "memory",
            "value": "4096"
        }, {
            "label": "系统盘大小",
            "hidden": false,
            "text": "80",
            "key": "systemDiskSize",
            "value": "80"
        }, {
            "label": "数据盘大小",
            "hidden": false,
            "text": "0",
            "key": "diskSize",
            "value": "0"
        }, {
            "label": "数据盘挂载点",
            "hidden": false,
            "text": "无",
            "key": "mountDir",
            "value": ""
        }, {
            "label": "机器名",
            "hidden": false,
            "text": "dwr-1115-02",
            "key": "vmName",
            "value": "dwr-1115-02"
        }, {
            "label": "计费方式",
            "hidden": false,
            "text": "按量付费",
            "key": "instanceChargeType",
            "value": "PostPaid"
        }, {
            "label": "默认租期",
            "hidden": false,
            "text": "一天",
            "key": "expiredTime",
            "value": "1"
        }, {
            "label": "默认回收策略",
            "hidden": false,
            "text": "到期立即回收",
            "key": "recycleStrategy",
            "value": "-2"
        }, {
            "label": "文件夹",
            "hidden": false,
            "text": "cmp/D",
            "key": "folderName",
            "value": "cmp/D"
        }, {
            "label": "hostname与机器名一致",
            "hidden": false,
            "text": "否",
            "key": "hostnameConsistentVMName",
            "value": "false"
        }, {
            "label": "hostname",
            "hidden": false,
            "text": "bjpvldcmpap08468",
            "key": "hostname",
            "value": "bjpvldcmpap08468"
        }, {
            "label": "备注是否必填",
            "hidden": false,
            "text": "否",
            "key": "remarkBol",
            "value": "false"
        }, {
            "label": "备注",
            "hidden": false,
            "text": "dwr-1115-02-re",
            "key": "remark",
            "value": "dwr-1115-02-re"
        }, {
            "label": "重置密码",
            "hidden": false,
            "text": "重置模板系统管理员密码",
            "key": "changePasswordPolicy",
            "value": "changeTemplateUserPwd"
        }, {
            "label": "访客用户名",
            "hidden": false,
            "text": "root",
            "key": "guestUser",
            "value": "root"
        }, {
            "label": "登录密码",
            "hidden": false,
            "text": "cnJkZzR1ZW5GaXQyY2xvdWRAMjAyNHh5OTR0emtp",
            "key": "loginPassword",
            "value": "cnJkZzR1ZW5GaXQyY2xvdWRAMjAyNHh5OTR0emtp"
        }, {
            "label": "是否加入域",
            "hidden": false,
            "text": "否",
            "key": "addDomain",
            "value": "false"
        }, {
            "label": "域名",
            "hidden": false,
            "text": "无",
            "key": "domainName"
        }, {
            "label": "域用户",
            "hidden": false,
            "text": "无",
            "key": "domainUserName"
        }, {
            "label": "域用户",
            "hidden": false,
            "text": "无",
            "key": "domainUserPasswd"
        }, {
            "label": "是否加入F5负载均衡",
            "hidden": false,
            "text": "否",
            "key": "addF5Pool",
            "value": "false"
        }, {
            "label": "挂载F5策略",
            "hidden": false,
            "text": "无",
            "key": "F5Policy"
        }, {
            "label": "F5分区",
            "hidden": false,
            "text": "Common (北京 F5（内网）)",
            "key": "f5Partition",
            "value": "52ae5952-2263-4100-94e9-a55a0ea4c479"
        }, {
            "label": "F5 Virtual Server",
            "hidden": false,
            "text": "kms_test_work_10.11.225.108_443",
            "key": "f5VirtualId",
            "value": "01fbb5b4-dae6-456b-86f9-3529bfb26630"
        }, {
            "label": "虚拟服务器IP",
            "hidden": false,
            "text": "无",
            "key": "vsIp"
        }, {
            "label": "虚拟服务器端口",
            "hidden": false,
            "text": "无",
            "key": "vsPort"
        }, {
            "label": "负载策略",
            "hidden": false,
            "text": "无",
            "key": "vsLoadPolicy"
        }, {
            "label": "负载端口",
            "hidden": false,
            "text": "无",
            "key": "f5MemberPort"
        }, {
            "label": "是否进行备份",
            "hidden": false,
            "text": "否",
            "key": "addVeeam",
            "value": "false"
        }, {
            "label": "是否开启所有内存预留",
            "hidden": false,
            "text": "否",
            "key": "memoryReservation",
            "value": "false"
        }, {
            "label": "开启内网带宽限制",
            "hidden": false,
            "text": "否",
            "key": "bandwidthLimitSwitch",
            "value": "false"
        }, {
            "label": "内网带宽(Mbit/s)",
            "hidden": false,
            "text": "10000",
            "key": "bandwidthSize",
            "value": "10000"
        }, {
            "label": "是否启用CPU热添加",
            "hidden": false,
            "text": "是",
            "key": "cpuHotAddEnabled",
            "value": "true"
        }, {
            "label": "是否启用内存热添加",
            "hidden": false,
            "text": "是",
            "key": "memHotAddEnabled",
            "value": "true"
        }, {
            "label": "审批自定义实例规格",
            "hidden": false,
            "text": "否",
            "key": "approveCustomInstanceType",
            "value": "false"
        }, {
            "label": "是否安装监控代理",
            "hidden": false,
            "text": "否",
            "key": "monitoringAlarm",
            "value": "false"
        }, {
            "label": "安全组",
            "hidden": false,
            "text": "[]",
            "key": "userSecurityGroupNames",
            "value": "[]"
        }, {
            "label": "主机名自动转为全小写",
            "hidden": false,
            "text": "是",
            "key": "__lowercase_vm_name",
            "value": "true"
        }, {
            "label": "自动生成密码",
            "hidden": false,
            "text": "否",
            "key": "generatePassword",
            "value": "false"
        }, {
            "label": "密码生成规则",
            "hidden": false,
            "text": "小写字母;大写字母;数字;特殊字符;",
            "key": "generatePasswordRule",
            "value": "[\"lowercase\",\"uppercase\",\"number\",\"speChars\"]"
        }, {
            "label": "账号/KEY(权限)",
            "hidden": false,
            "text": "工作空间可维护",
            "key": "passwordPermission",
            "value": "edit"
        }, {
            "label": "密码长度必须在12到26之间",
            "hidden": false,
            "text": "16",
            "key": "generatePasswordLength",
            "value": "16"
        }, {
            "label": "磁盘格式",
            "hidden": false,
            "text": "无",
            "key": "diskType",
            "value": ""
        }, {
            "label": "vm_os_version",
            "hidden": false,
            "text": "8.7",
            "key": "vm_os_version",
            "value": "8.7"
        }, {
            "label": "租期",
            "hidden": false,
            "text": "一天",
            "key": "expiredTimeStr",
            "value": "一天"
        }, {
            "label": "版本",
            "hidden": false,
            "text": "redhat",
            "key": "vm_os",
            "value": "redhat"
        }, {
            "label": "租期",
            "hidden": false,
            "text": "2024-11-15T18:49:25.417Z",
            "key": "expiredTime",
            "value": "2024-11-15T18:49:25.417Z"
        }]
    }],
    "applicant": "lijun.zhang",
    "resourceType": "VIRTUALMACHINE"
}

