package com.fit2cloud.itsm.dao;

import com.fit2cloud.itsm.model.PciApiParameterMapping;
import com.fit2cloud.itsm.model.PciApiParameterMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PciApiParameterMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    long countByExample(PciApiParameterMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    int deleteByExample(PciApiParameterMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    int insert(PciApiParameterMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    int insertSelective(PciApiParameterMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    List<PciApiParameterMapping> selectByExampleWithBLOBs(PciApiParameterMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    List<PciApiParameterMapping> selectByExample(PciApiParameterMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    PciApiParameterMapping selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PciApiParameterMapping record, @Param("example") PciApiParameterMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PciApiParameterMapping record, @Param("example") PciApiParameterMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PciApiParameterMapping record, @Param("example") PciApiParameterMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PciApiParameterMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PciApiParameterMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PciApiParameterMapping record);
}