package com.fit2cloud.itsm.dao;

import com.fit2cloud.itsm.model.PciApiEndpoint;
import com.fit2cloud.itsm.model.PciApiEndpointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PciApiEndpointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_endpoint
     *
     * @mbg.generated
     */
    long countByExample(PciApiEndpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_endpoint
     *
     * @mbg.generated
     */
    int deleteByExample(PciApiEndpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_endpoint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_endpoint
     *
     * @mbg.generated
     */
    int insert(PciApiEndpoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_endpoint
     *
     * @mbg.generated
     */
    int insertSelective(PciApiEndpoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_endpoint
     *
     * @mbg.generated
     */
    List<PciApiEndpoint> selectByExample(PciApiEndpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_endpoint
     *
     * @mbg.generated
     */
    PciApiEndpoint selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_endpoint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PciApiEndpoint record, @Param("example") PciApiEndpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_endpoint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PciApiEndpoint record, @Param("example") PciApiEndpointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_endpoint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PciApiEndpoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_endpoint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PciApiEndpoint record);
}