package com.fit2cloud.itsm.dao;

import com.fit2cloud.itsm.model.PciApiLogContent;
import com.fit2cloud.itsm.model.PciApiLogContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PciApiLogContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log_content
     *
     * @mbg.generated
     */
    long countByExample(PciApiLogContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log_content
     *
     * @mbg.generated
     */
    int deleteByExample(PciApiLogContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log_content
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String pciApiLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log_content
     *
     * @mbg.generated
     */
    int insert(PciApiLogContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log_content
     *
     * @mbg.generated
     */
    int insertSelective(PciApiLogContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log_content
     *
     * @mbg.generated
     */
    List<PciApiLogContent> selectByExampleWithBLOBs(PciApiLogContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log_content
     *
     * @mbg.generated
     */
    List<PciApiLogContent> selectByExample(PciApiLogContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log_content
     *
     * @mbg.generated
     */
    PciApiLogContent selectByPrimaryKey(String pciApiLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log_content
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PciApiLogContent record, @Param("example") PciApiLogContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log_content
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PciApiLogContent record, @Param("example") PciApiLogContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log_content
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PciApiLogContent record, @Param("example") PciApiLogContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PciApiLogContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PciApiLogContent record);
}