package com.fit2cloud.itsm.dao;

import com.fit2cloud.itsm.model.PciApiLog;
import com.fit2cloud.itsm.model.PciApiLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PciApiLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log
     *
     * @mbg.generated
     */
    long countByExample(PciApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log
     *
     * @mbg.generated
     */
    int deleteByExample(PciApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log
     *
     * @mbg.generated
     */
    int insert(PciApiLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log
     *
     * @mbg.generated
     */
    int insertSelective(PciApiLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log
     *
     * @mbg.generated
     */
    List<PciApiLog> selectByExample(PciApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log
     *
     * @mbg.generated
     */
    PciApiLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PciApiLog record, @Param("example") PciApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PciApiLog record, @Param("example") PciApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PciApiLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PciApiLog record);
}