package com.fit2cloud.itsm.dao;

import com.fit2cloud.itsm.model.PciApiAccount;
import com.fit2cloud.itsm.model.PciApiAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PciApiAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_account
     *
     * @mbg.generated
     */
    long countByExample(PciApiAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_account
     *
     * @mbg.generated
     */
    int deleteByExample(PciApiAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_account
     *
     * @mbg.generated
     */
    int insert(PciApiAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_account
     *
     * @mbg.generated
     */
    int insertSelective(PciApiAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_account
     *
     * @mbg.generated
     */
    List<PciApiAccount> selectByExampleWithBLOBs(PciApiAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_account
     *
     * @mbg.generated
     */
    List<PciApiAccount> selectByExample(PciApiAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_account
     *
     * @mbg.generated
     */
    PciApiAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PciApiAccount record, @Param("example") PciApiAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_account
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PciApiAccount record, @Param("example") PciApiAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PciApiAccount record, @Param("example") PciApiAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PciApiAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PciApiAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PciApiAccount record);
}