package com.fit2cloud.itsm.dao;

import com.fit2cloud.itsm.model.PciApiParameterMappingDictionary;
import com.fit2cloud.itsm.model.PciApiParameterMappingDictionaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PciApiParameterMappingDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    long countByExample(PciApiParameterMappingDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    int deleteByExample(PciApiParameterMappingDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    int insert(PciApiParameterMappingDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    int insertSelective(PciApiParameterMappingDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    List<PciApiParameterMappingDictionary> selectByExample(PciApiParameterMappingDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    PciApiParameterMappingDictionary selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PciApiParameterMappingDictionary record, @Param("example") PciApiParameterMappingDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PciApiParameterMappingDictionary record, @Param("example") PciApiParameterMappingDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PciApiParameterMappingDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PciApiParameterMappingDictionary record);
}