package com.fit2cloud.itsm.dao;

import com.fit2cloud.itsm.model.PciExternalSystemOrgMappingExample;
import com.fit2cloud.itsm.model.PciExternalSystemOrgMappingKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PciExternalSystemOrgMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org_mapping
     *
     * @mbg.generated
     */
    long countByExample(PciExternalSystemOrgMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org_mapping
     *
     * @mbg.generated
     */
    int deleteByExample(PciExternalSystemOrgMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org_mapping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(PciExternalSystemOrgMappingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org_mapping
     *
     * @mbg.generated
     */
    int insert(PciExternalSystemOrgMappingKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org_mapping
     *
     * @mbg.generated
     */
    int insertSelective(PciExternalSystemOrgMappingKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org_mapping
     *
     * @mbg.generated
     */
    List<PciExternalSystemOrgMappingKey> selectByExample(PciExternalSystemOrgMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org_mapping
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PciExternalSystemOrgMappingKey record, @Param("example") PciExternalSystemOrgMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org_mapping
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PciExternalSystemOrgMappingKey record, @Param("example") PciExternalSystemOrgMappingExample example);
}