package com.fit2cloud.itsm.dao;

import com.fit2cloud.itsm.model.PciExternalSystemOrg;
import com.fit2cloud.itsm.model.PciExternalSystemOrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PciExternalSystemOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    long countByExample(PciExternalSystemOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    int deleteByExample(PciExternalSystemOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    int insert(PciExternalSystemOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    int insertSelective(PciExternalSystemOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    List<PciExternalSystemOrg> selectByExample(PciExternalSystemOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    PciExternalSystemOrg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PciExternalSystemOrg record, @Param("example") PciExternalSystemOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PciExternalSystemOrg record, @Param("example") PciExternalSystemOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PciExternalSystemOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PciExternalSystemOrg record);
}