package com.fit2cloud.itsm.dao;

import com.fit2cloud.itsm.model.PciExternalSystemSyncDetailLog;
import com.fit2cloud.itsm.model.PciExternalSystemSyncDetailLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PciExternalSystemSyncDetailLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    long countByExample(PciExternalSystemSyncDetailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    int deleteByExample(PciExternalSystemSyncDetailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    int insert(PciExternalSystemSyncDetailLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    int insertSelective(PciExternalSystemSyncDetailLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    List<PciExternalSystemSyncDetailLog> selectByExampleWithBLOBs(PciExternalSystemSyncDetailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    List<PciExternalSystemSyncDetailLog> selectByExample(PciExternalSystemSyncDetailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    PciExternalSystemSyncDetailLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PciExternalSystemSyncDetailLog record, @Param("example") PciExternalSystemSyncDetailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PciExternalSystemSyncDetailLog record, @Param("example") PciExternalSystemSyncDetailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PciExternalSystemSyncDetailLog record, @Param("example") PciExternalSystemSyncDetailLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PciExternalSystemSyncDetailLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PciExternalSystemSyncDetailLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PciExternalSystemSyncDetailLog record);
}