package com.fit2cloud.itsm.dao;

import com.fit2cloud.itsm.model.PciExternalSystemUser;
import com.fit2cloud.itsm.model.PciExternalSystemUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PciExternalSystemUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_user
     *
     * @mbg.generated
     */
    long countByExample(PciExternalSystemUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_user
     *
     * @mbg.generated
     */
    int deleteByExample(PciExternalSystemUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_user
     *
     * @mbg.generated
     */
    int insert(PciExternalSystemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_user
     *
     * @mbg.generated
     */
    int insertSelective(PciExternalSystemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_user
     *
     * @mbg.generated
     */
    List<PciExternalSystemUser> selectByExample(PciExternalSystemUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_user
     *
     * @mbg.generated
     */
    PciExternalSystemUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PciExternalSystemUser record, @Param("example") PciExternalSystemUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PciExternalSystemUser record, @Param("example") PciExternalSystemUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PciExternalSystemUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PciExternalSystemUser record);
}