package com.fit2cloud.itsm.dao;

import com.fit2cloud.itsm.model.PciProcess;
import com.fit2cloud.itsm.model.PciProcessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PciProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_process
     *
     * @mbg.generated
     */
    long countByExample(PciProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_process
     *
     * @mbg.generated
     */
    int deleteByExample(PciProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_process
     *
     * @mbg.generated
     */
    int insert(PciProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_process
     *
     * @mbg.generated
     */
    int insertSelective(PciProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_process
     *
     * @mbg.generated
     */
    List<PciProcess> selectByExample(PciProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_process
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PciProcess record, @Param("example") PciProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_process
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PciProcess record, @Param("example") PciProcessExample example);
}