package com.fit2cloud.itsm.dao;

import com.fit2cloud.itsm.model.PciSyncOrgSetting;
import com.fit2cloud.itsm.model.PciSyncOrgSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PciSyncOrgSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_org_setting
     *
     * @mbg.generated
     */
    long countByExample(PciSyncOrgSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_org_setting
     *
     * @mbg.generated
     */
    int deleteByExample(PciSyncOrgSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_org_setting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_org_setting
     *
     * @mbg.generated
     */
    int insert(PciSyncOrgSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_org_setting
     *
     * @mbg.generated
     */
    int insertSelective(PciSyncOrgSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_org_setting
     *
     * @mbg.generated
     */
    List<PciSyncOrgSetting> selectByExample(PciSyncOrgSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_org_setting
     *
     * @mbg.generated
     */
    PciSyncOrgSetting selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_org_setting
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PciSyncOrgSetting record, @Param("example") PciSyncOrgSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_org_setting
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PciSyncOrgSetting record, @Param("example") PciSyncOrgSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_org_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PciSyncOrgSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_org_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PciSyncOrgSetting record);
}