package com.fit2cloud.itsm.dao;

import com.fit2cloud.itsm.model.PciSyncUserSetting;
import com.fit2cloud.itsm.model.PciSyncUserSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PciSyncUserSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_user_setting
     *
     * @mbg.generated
     */
    long countByExample(PciSyncUserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_user_setting
     *
     * @mbg.generated
     */
    int deleteByExample(PciSyncUserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_user_setting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_user_setting
     *
     * @mbg.generated
     */
    int insert(PciSyncUserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_user_setting
     *
     * @mbg.generated
     */
    int insertSelective(PciSyncUserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_user_setting
     *
     * @mbg.generated
     */
    List<PciSyncUserSetting> selectByExample(PciSyncUserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_user_setting
     *
     * @mbg.generated
     */
    PciSyncUserSetting selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_user_setting
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PciSyncUserSetting record, @Param("example") PciSyncUserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_user_setting
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PciSyncUserSetting record, @Param("example") PciSyncUserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_user_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PciSyncUserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_sync_user_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PciSyncUserSetting record);
}