package com.fit2cloud.itsm.dao;

import com.fit2cloud.itsm.model.VmCloudServer;
import com.fit2cloud.itsm.model.dto.VmCloudServerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VmCloudServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_cloud_server
     *
     * @mbg.generated
     */
    long countByExample(VmCloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_cloud_server
     *
     * @mbg.generated
     */
    int deleteByExample(VmCloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_cloud_server
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cloudServerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_cloud_server
     *
     * @mbg.generated
     */
    int insert(VmCloudServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_cloud_server
     *
     * @mbg.generated
     */
    int insertSelective(VmCloudServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_cloud_server
     *
     * @mbg.generated
     */
    List<VmCloudServer> selectByExampleWithBLOBs(VmCloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_cloud_server
     *
     * @mbg.generated
     */
    List<VmCloudServer> selectByExample(VmCloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_cloud_server
     *
     * @mbg.generated
     */
    VmCloudServer selectByPrimaryKey(String cloudServerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_cloud_server
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VmCloudServer record, @Param("example") VmCloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_cloud_server
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") VmCloudServer record, @Param("example") VmCloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_cloud_server
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VmCloudServer record, @Param("example") VmCloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_cloud_server
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VmCloudServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_cloud_server
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(VmCloudServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vm_cloud_server
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VmCloudServer record);
}