package com.fit2cloud.itsm.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

public class PciApiParameterMapping implements Serializable {
    @ApiModelProperty("主键索引")
    private String id;

    @ApiModelProperty("API 地址 ID")
    private String apiId;

    @ApiModelProperty("源字段名")
    private String originField;

    @ApiModelProperty("源字段类型")
    private String originFieldType;

    @ApiModelProperty("目标字段名")
    private String targetField;

    @ApiModelProperty("目标字段类型")
    private String targetFieldType;

    @ApiModelProperty("修改时间")
    private Date updateTime;

    @ApiModelProperty("源字段来源")
    private String originFieldSource;

    @ApiModelProperty("源表")
    private String originFieldTable;

    @ApiModelProperty("源字段名")
    private String originFieldName;

    @ApiModelProperty("字段标识")
    private String fieldTag;

    @ApiModelProperty("描述")
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping.id
     *
     * @return the value of pci_api_parameter_mapping.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping.id
     *
     * @param id the value for pci_api_parameter_mapping.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping.api_id
     *
     * @return the value of pci_api_parameter_mapping.api_id
     *
     * @mbg.generated
     */
    public String getApiId() {
        return apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping.api_id
     *
     * @param apiId the value for pci_api_parameter_mapping.api_id
     *
     * @mbg.generated
     */
    public void setApiId(String apiId) {
        this.apiId = apiId == null ? null : apiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping.origin_field
     *
     * @return the value of pci_api_parameter_mapping.origin_field
     *
     * @mbg.generated
     */
    public String getOriginField() {
        return originField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping.origin_field
     *
     * @param originField the value for pci_api_parameter_mapping.origin_field
     *
     * @mbg.generated
     */
    public void setOriginField(String originField) {
        this.originField = originField == null ? null : originField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping.origin_field_type
     *
     * @return the value of pci_api_parameter_mapping.origin_field_type
     *
     * @mbg.generated
     */
    public String getOriginFieldType() {
        return originFieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping.origin_field_type
     *
     * @param originFieldType the value for pci_api_parameter_mapping.origin_field_type
     *
     * @mbg.generated
     */
    public void setOriginFieldType(String originFieldType) {
        this.originFieldType = originFieldType == null ? null : originFieldType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping.target_field
     *
     * @return the value of pci_api_parameter_mapping.target_field
     *
     * @mbg.generated
     */
    public String getTargetField() {
        return targetField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping.target_field
     *
     * @param targetField the value for pci_api_parameter_mapping.target_field
     *
     * @mbg.generated
     */
    public void setTargetField(String targetField) {
        this.targetField = targetField == null ? null : targetField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping.target_field_type
     *
     * @return the value of pci_api_parameter_mapping.target_field_type
     *
     * @mbg.generated
     */
    public String getTargetFieldType() {
        return targetFieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping.target_field_type
     *
     * @param targetFieldType the value for pci_api_parameter_mapping.target_field_type
     *
     * @mbg.generated
     */
    public void setTargetFieldType(String targetFieldType) {
        this.targetFieldType = targetFieldType == null ? null : targetFieldType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping.update_time
     *
     * @return the value of pci_api_parameter_mapping.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping.update_time
     *
     * @param updateTime the value for pci_api_parameter_mapping.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping.origin_field_source
     *
     * @return the value of pci_api_parameter_mapping.origin_field_source
     *
     * @mbg.generated
     */
    public String getOriginFieldSource() {
        return originFieldSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping.origin_field_source
     *
     * @param originFieldSource the value for pci_api_parameter_mapping.origin_field_source
     *
     * @mbg.generated
     */
    public void setOriginFieldSource(String originFieldSource) {
        this.originFieldSource = originFieldSource == null ? null : originFieldSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping.origin_field_table
     *
     * @return the value of pci_api_parameter_mapping.origin_field_table
     *
     * @mbg.generated
     */
    public String getOriginFieldTable() {
        return originFieldTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping.origin_field_table
     *
     * @param originFieldTable the value for pci_api_parameter_mapping.origin_field_table
     *
     * @mbg.generated
     */
    public void setOriginFieldTable(String originFieldTable) {
        this.originFieldTable = originFieldTable == null ? null : originFieldTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping.origin_field_name
     *
     * @return the value of pci_api_parameter_mapping.origin_field_name
     *
     * @mbg.generated
     */
    public String getOriginFieldName() {
        return originFieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping.origin_field_name
     *
     * @param originFieldName the value for pci_api_parameter_mapping.origin_field_name
     *
     * @mbg.generated
     */
    public void setOriginFieldName(String originFieldName) {
        this.originFieldName = originFieldName == null ? null : originFieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping.field_tag
     *
     * @return the value of pci_api_parameter_mapping.field_tag
     *
     * @mbg.generated
     */
    public String getFieldTag() {
        return fieldTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping.field_tag
     *
     * @param fieldTag the value for pci_api_parameter_mapping.field_tag
     *
     * @mbg.generated
     */
    public void setFieldTag(String fieldTag) {
        this.fieldTag = fieldTag == null ? null : fieldTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping.description
     *
     * @return the value of pci_api_parameter_mapping.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping.description
     *
     * @param description the value for pci_api_parameter_mapping.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}