package com.fit2cloud.itsm.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

public class PciApiEndpoint implements Serializable {
    @ApiModelProperty("主键索引")
    private String id;

    @ApiModelProperty("API 功能")
    private String apiType;

    @ApiModelProperty("API 账号 ID")
    private String apiAccount;

    @ApiModelProperty("API 地址")
    private String endpoint;

    @ApiModelProperty("请求方法(GET/POST)")
    private String method;

    @ApiModelProperty("请求参数模版")
    private String customContent;

    @ApiModelProperty("请求参数模版")
    private String requestTemplate;

    @ApiModelProperty("修改时间")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_api_endpoint
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_endpoint.id
     *
     * @return the value of pci_api_endpoint.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_endpoint.id
     *
     * @param id the value for pci_api_endpoint.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_endpoint.api_type
     *
     * @return the value of pci_api_endpoint.api_type
     *
     * @mbg.generated
     */
    public String getApiType() {
        return apiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_endpoint.api_type
     *
     * @param apiType the value for pci_api_endpoint.api_type
     *
     * @mbg.generated
     */
    public void setApiType(String apiType) {
        this.apiType = apiType == null ? null : apiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_endpoint.api_account
     *
     * @return the value of pci_api_endpoint.api_account
     *
     * @mbg.generated
     */
    public String getApiAccount() {
        return apiAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_endpoint.api_account
     *
     * @param apiAccount the value for pci_api_endpoint.api_account
     *
     * @mbg.generated
     */
    public void setApiAccount(String apiAccount) {
        this.apiAccount = apiAccount == null ? null : apiAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_endpoint.endpoint
     *
     * @return the value of pci_api_endpoint.endpoint
     *
     * @mbg.generated
     */
    public String getEndpoint() {
        return endpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_endpoint.endpoint
     *
     * @param endpoint the value for pci_api_endpoint.endpoint
     *
     * @mbg.generated
     */
    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint == null ? null : endpoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_endpoint.method
     *
     * @return the value of pci_api_endpoint.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_endpoint.method
     *
     * @param method the value for pci_api_endpoint.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_endpoint.custom_content
     *
     * @return the value of pci_api_endpoint.custom_content
     *
     * @mbg.generated
     */
    public String getCustomContent() {
        return customContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_endpoint.custom_content
     *
     * @param customContent the value for pci_api_endpoint.custom_content
     *
     * @mbg.generated
     */
    public void setCustomContent(String customContent) {
        this.customContent = customContent == null ? null : customContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_endpoint.request_template
     *
     * @return the value of pci_api_endpoint.request_template
     *
     * @mbg.generated
     */
    public String getRequestTemplate() {
        return requestTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_endpoint.request_template
     *
     * @param requestTemplate the value for pci_api_endpoint.request_template
     *
     * @mbg.generated
     */
    public void setRequestTemplate(String requestTemplate) {
        this.requestTemplate = requestTemplate == null ? null : requestTemplate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_endpoint.update_time
     *
     * @return the value of pci_api_endpoint.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_endpoint.update_time
     *
     * @param updateTime the value for pci_api_endpoint.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}