package com.fit2cloud.itsm.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class PciApiLogContent implements Serializable {
    @ApiModelProperty("主键索引")
    private String pciApiLogId;

    @ApiModelProperty("日志信息")
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_api_log_content
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_log_content.pci_api_log_id
     *
     * @return the value of pci_api_log_content.pci_api_log_id
     *
     * @mbg.generated
     */
    public String getPciApiLogId() {
        return pciApiLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_log_content.pci_api_log_id
     *
     * @param pciApiLogId the value for pci_api_log_content.pci_api_log_id
     *
     * @mbg.generated
     */
    public void setPciApiLogId(String pciApiLogId) {
        this.pciApiLogId = pciApiLogId == null ? null : pciApiLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_log_content.message
     *
     * @return the value of pci_api_log_content.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_log_content.message
     *
     * @param message the value for pci_api_log_content.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}