package com.fit2cloud.itsm.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PciApiParameterMappingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    public PciApiParameterMappingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andApiIdIsNull() {
            addCriterion("api_id is null");
            return (Criteria) this;
        }

        public Criteria andApiIdIsNotNull() {
            addCriterion("api_id is not null");
            return (Criteria) this;
        }

        public Criteria andApiIdEqualTo(String value) {
            addCriterion("api_id =", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdNotEqualTo(String value) {
            addCriterion("api_id <>", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdGreaterThan(String value) {
            addCriterion("api_id >", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdGreaterThanOrEqualTo(String value) {
            addCriterion("api_id >=", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdLessThan(String value) {
            addCriterion("api_id <", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdLessThanOrEqualTo(String value) {
            addCriterion("api_id <=", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdLike(String value) {
            addCriterion("api_id like", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdNotLike(String value) {
            addCriterion("api_id not like", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdIn(List<String> values) {
            addCriterion("api_id in", values, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdNotIn(List<String> values) {
            addCriterion("api_id not in", values, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdBetween(String value1, String value2) {
            addCriterion("api_id between", value1, value2, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdNotBetween(String value1, String value2) {
            addCriterion("api_id not between", value1, value2, "apiId");
            return (Criteria) this;
        }

        public Criteria andOriginFieldIsNull() {
            addCriterion("origin_field is null");
            return (Criteria) this;
        }

        public Criteria andOriginFieldIsNotNull() {
            addCriterion("origin_field is not null");
            return (Criteria) this;
        }

        public Criteria andOriginFieldEqualTo(String value) {
            addCriterion("origin_field =", value, "originField");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNotEqualTo(String value) {
            addCriterion("origin_field <>", value, "originField");
            return (Criteria) this;
        }

        public Criteria andOriginFieldGreaterThan(String value) {
            addCriterion("origin_field >", value, "originField");
            return (Criteria) this;
        }

        public Criteria andOriginFieldGreaterThanOrEqualTo(String value) {
            addCriterion("origin_field >=", value, "originField");
            return (Criteria) this;
        }

        public Criteria andOriginFieldLessThan(String value) {
            addCriterion("origin_field <", value, "originField");
            return (Criteria) this;
        }

        public Criteria andOriginFieldLessThanOrEqualTo(String value) {
            addCriterion("origin_field <=", value, "originField");
            return (Criteria) this;
        }

        public Criteria andOriginFieldLike(String value) {
            addCriterion("origin_field like", value, "originField");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNotLike(String value) {
            addCriterion("origin_field not like", value, "originField");
            return (Criteria) this;
        }

        public Criteria andOriginFieldIn(List<String> values) {
            addCriterion("origin_field in", values, "originField");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNotIn(List<String> values) {
            addCriterion("origin_field not in", values, "originField");
            return (Criteria) this;
        }

        public Criteria andOriginFieldBetween(String value1, String value2) {
            addCriterion("origin_field between", value1, value2, "originField");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNotBetween(String value1, String value2) {
            addCriterion("origin_field not between", value1, value2, "originField");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTypeIsNull() {
            addCriterion("origin_field_type is null");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTypeIsNotNull() {
            addCriterion("origin_field_type is not null");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTypeEqualTo(String value) {
            addCriterion("origin_field_type =", value, "originFieldType");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTypeNotEqualTo(String value) {
            addCriterion("origin_field_type <>", value, "originFieldType");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTypeGreaterThan(String value) {
            addCriterion("origin_field_type >", value, "originFieldType");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTypeGreaterThanOrEqualTo(String value) {
            addCriterion("origin_field_type >=", value, "originFieldType");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTypeLessThan(String value) {
            addCriterion("origin_field_type <", value, "originFieldType");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTypeLessThanOrEqualTo(String value) {
            addCriterion("origin_field_type <=", value, "originFieldType");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTypeLike(String value) {
            addCriterion("origin_field_type like", value, "originFieldType");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTypeNotLike(String value) {
            addCriterion("origin_field_type not like", value, "originFieldType");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTypeIn(List<String> values) {
            addCriterion("origin_field_type in", values, "originFieldType");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTypeNotIn(List<String> values) {
            addCriterion("origin_field_type not in", values, "originFieldType");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTypeBetween(String value1, String value2) {
            addCriterion("origin_field_type between", value1, value2, "originFieldType");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTypeNotBetween(String value1, String value2) {
            addCriterion("origin_field_type not between", value1, value2, "originFieldType");
            return (Criteria) this;
        }

        public Criteria andTargetFieldIsNull() {
            addCriterion("target_field is null");
            return (Criteria) this;
        }

        public Criteria andTargetFieldIsNotNull() {
            addCriterion("target_field is not null");
            return (Criteria) this;
        }

        public Criteria andTargetFieldEqualTo(String value) {
            addCriterion("target_field =", value, "targetField");
            return (Criteria) this;
        }

        public Criteria andTargetFieldNotEqualTo(String value) {
            addCriterion("target_field <>", value, "targetField");
            return (Criteria) this;
        }

        public Criteria andTargetFieldGreaterThan(String value) {
            addCriterion("target_field >", value, "targetField");
            return (Criteria) this;
        }

        public Criteria andTargetFieldGreaterThanOrEqualTo(String value) {
            addCriterion("target_field >=", value, "targetField");
            return (Criteria) this;
        }

        public Criteria andTargetFieldLessThan(String value) {
            addCriterion("target_field <", value, "targetField");
            return (Criteria) this;
        }

        public Criteria andTargetFieldLessThanOrEqualTo(String value) {
            addCriterion("target_field <=", value, "targetField");
            return (Criteria) this;
        }

        public Criteria andTargetFieldLike(String value) {
            addCriterion("target_field like", value, "targetField");
            return (Criteria) this;
        }

        public Criteria andTargetFieldNotLike(String value) {
            addCriterion("target_field not like", value, "targetField");
            return (Criteria) this;
        }

        public Criteria andTargetFieldIn(List<String> values) {
            addCriterion("target_field in", values, "targetField");
            return (Criteria) this;
        }

        public Criteria andTargetFieldNotIn(List<String> values) {
            addCriterion("target_field not in", values, "targetField");
            return (Criteria) this;
        }

        public Criteria andTargetFieldBetween(String value1, String value2) {
            addCriterion("target_field between", value1, value2, "targetField");
            return (Criteria) this;
        }

        public Criteria andTargetFieldNotBetween(String value1, String value2) {
            addCriterion("target_field not between", value1, value2, "targetField");
            return (Criteria) this;
        }

        public Criteria andTargetFieldTypeIsNull() {
            addCriterion("target_field_type is null");
            return (Criteria) this;
        }

        public Criteria andTargetFieldTypeIsNotNull() {
            addCriterion("target_field_type is not null");
            return (Criteria) this;
        }

        public Criteria andTargetFieldTypeEqualTo(String value) {
            addCriterion("target_field_type =", value, "targetFieldType");
            return (Criteria) this;
        }

        public Criteria andTargetFieldTypeNotEqualTo(String value) {
            addCriterion("target_field_type <>", value, "targetFieldType");
            return (Criteria) this;
        }

        public Criteria andTargetFieldTypeGreaterThan(String value) {
            addCriterion("target_field_type >", value, "targetFieldType");
            return (Criteria) this;
        }

        public Criteria andTargetFieldTypeGreaterThanOrEqualTo(String value) {
            addCriterion("target_field_type >=", value, "targetFieldType");
            return (Criteria) this;
        }

        public Criteria andTargetFieldTypeLessThan(String value) {
            addCriterion("target_field_type <", value, "targetFieldType");
            return (Criteria) this;
        }

        public Criteria andTargetFieldTypeLessThanOrEqualTo(String value) {
            addCriterion("target_field_type <=", value, "targetFieldType");
            return (Criteria) this;
        }

        public Criteria andTargetFieldTypeLike(String value) {
            addCriterion("target_field_type like", value, "targetFieldType");
            return (Criteria) this;
        }

        public Criteria andTargetFieldTypeNotLike(String value) {
            addCriterion("target_field_type not like", value, "targetFieldType");
            return (Criteria) this;
        }

        public Criteria andTargetFieldTypeIn(List<String> values) {
            addCriterion("target_field_type in", values, "targetFieldType");
            return (Criteria) this;
        }

        public Criteria andTargetFieldTypeNotIn(List<String> values) {
            addCriterion("target_field_type not in", values, "targetFieldType");
            return (Criteria) this;
        }

        public Criteria andTargetFieldTypeBetween(String value1, String value2) {
            addCriterion("target_field_type between", value1, value2, "targetFieldType");
            return (Criteria) this;
        }

        public Criteria andTargetFieldTypeNotBetween(String value1, String value2) {
            addCriterion("target_field_type not between", value1, value2, "targetFieldType");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andOriginFieldSourceIsNull() {
            addCriterion("origin_field_source is null");
            return (Criteria) this;
        }

        public Criteria andOriginFieldSourceIsNotNull() {
            addCriterion("origin_field_source is not null");
            return (Criteria) this;
        }

        public Criteria andOriginFieldSourceEqualTo(String value) {
            addCriterion("origin_field_source =", value, "originFieldSource");
            return (Criteria) this;
        }

        public Criteria andOriginFieldSourceNotEqualTo(String value) {
            addCriterion("origin_field_source <>", value, "originFieldSource");
            return (Criteria) this;
        }

        public Criteria andOriginFieldSourceGreaterThan(String value) {
            addCriterion("origin_field_source >", value, "originFieldSource");
            return (Criteria) this;
        }

        public Criteria andOriginFieldSourceGreaterThanOrEqualTo(String value) {
            addCriterion("origin_field_source >=", value, "originFieldSource");
            return (Criteria) this;
        }

        public Criteria andOriginFieldSourceLessThan(String value) {
            addCriterion("origin_field_source <", value, "originFieldSource");
            return (Criteria) this;
        }

        public Criteria andOriginFieldSourceLessThanOrEqualTo(String value) {
            addCriterion("origin_field_source <=", value, "originFieldSource");
            return (Criteria) this;
        }

        public Criteria andOriginFieldSourceLike(String value) {
            addCriterion("origin_field_source like", value, "originFieldSource");
            return (Criteria) this;
        }

        public Criteria andOriginFieldSourceNotLike(String value) {
            addCriterion("origin_field_source not like", value, "originFieldSource");
            return (Criteria) this;
        }

        public Criteria andOriginFieldSourceIn(List<String> values) {
            addCriterion("origin_field_source in", values, "originFieldSource");
            return (Criteria) this;
        }

        public Criteria andOriginFieldSourceNotIn(List<String> values) {
            addCriterion("origin_field_source not in", values, "originFieldSource");
            return (Criteria) this;
        }

        public Criteria andOriginFieldSourceBetween(String value1, String value2) {
            addCriterion("origin_field_source between", value1, value2, "originFieldSource");
            return (Criteria) this;
        }

        public Criteria andOriginFieldSourceNotBetween(String value1, String value2) {
            addCriterion("origin_field_source not between", value1, value2, "originFieldSource");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTableIsNull() {
            addCriterion("origin_field_table is null");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTableIsNotNull() {
            addCriterion("origin_field_table is not null");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTableEqualTo(String value) {
            addCriterion("origin_field_table =", value, "originFieldTable");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTableNotEqualTo(String value) {
            addCriterion("origin_field_table <>", value, "originFieldTable");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTableGreaterThan(String value) {
            addCriterion("origin_field_table >", value, "originFieldTable");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTableGreaterThanOrEqualTo(String value) {
            addCriterion("origin_field_table >=", value, "originFieldTable");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTableLessThan(String value) {
            addCriterion("origin_field_table <", value, "originFieldTable");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTableLessThanOrEqualTo(String value) {
            addCriterion("origin_field_table <=", value, "originFieldTable");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTableLike(String value) {
            addCriterion("origin_field_table like", value, "originFieldTable");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTableNotLike(String value) {
            addCriterion("origin_field_table not like", value, "originFieldTable");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTableIn(List<String> values) {
            addCriterion("origin_field_table in", values, "originFieldTable");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTableNotIn(List<String> values) {
            addCriterion("origin_field_table not in", values, "originFieldTable");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTableBetween(String value1, String value2) {
            addCriterion("origin_field_table between", value1, value2, "originFieldTable");
            return (Criteria) this;
        }

        public Criteria andOriginFieldTableNotBetween(String value1, String value2) {
            addCriterion("origin_field_table not between", value1, value2, "originFieldTable");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNameIsNull() {
            addCriterion("origin_field_name is null");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNameIsNotNull() {
            addCriterion("origin_field_name is not null");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNameEqualTo(String value) {
            addCriterion("origin_field_name =", value, "originFieldName");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNameNotEqualTo(String value) {
            addCriterion("origin_field_name <>", value, "originFieldName");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNameGreaterThan(String value) {
            addCriterion("origin_field_name >", value, "originFieldName");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNameGreaterThanOrEqualTo(String value) {
            addCriterion("origin_field_name >=", value, "originFieldName");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNameLessThan(String value) {
            addCriterion("origin_field_name <", value, "originFieldName");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNameLessThanOrEqualTo(String value) {
            addCriterion("origin_field_name <=", value, "originFieldName");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNameLike(String value) {
            addCriterion("origin_field_name like", value, "originFieldName");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNameNotLike(String value) {
            addCriterion("origin_field_name not like", value, "originFieldName");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNameIn(List<String> values) {
            addCriterion("origin_field_name in", values, "originFieldName");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNameNotIn(List<String> values) {
            addCriterion("origin_field_name not in", values, "originFieldName");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNameBetween(String value1, String value2) {
            addCriterion("origin_field_name between", value1, value2, "originFieldName");
            return (Criteria) this;
        }

        public Criteria andOriginFieldNameNotBetween(String value1, String value2) {
            addCriterion("origin_field_name not between", value1, value2, "originFieldName");
            return (Criteria) this;
        }

        public Criteria andFieldTagIsNull() {
            addCriterion("field_tag is null");
            return (Criteria) this;
        }

        public Criteria andFieldTagIsNotNull() {
            addCriterion("field_tag is not null");
            return (Criteria) this;
        }

        public Criteria andFieldTagEqualTo(String value) {
            addCriterion("field_tag =", value, "fieldTag");
            return (Criteria) this;
        }

        public Criteria andFieldTagNotEqualTo(String value) {
            addCriterion("field_tag <>", value, "fieldTag");
            return (Criteria) this;
        }

        public Criteria andFieldTagGreaterThan(String value) {
            addCriterion("field_tag >", value, "fieldTag");
            return (Criteria) this;
        }

        public Criteria andFieldTagGreaterThanOrEqualTo(String value) {
            addCriterion("field_tag >=", value, "fieldTag");
            return (Criteria) this;
        }

        public Criteria andFieldTagLessThan(String value) {
            addCriterion("field_tag <", value, "fieldTag");
            return (Criteria) this;
        }

        public Criteria andFieldTagLessThanOrEqualTo(String value) {
            addCriterion("field_tag <=", value, "fieldTag");
            return (Criteria) this;
        }

        public Criteria andFieldTagLike(String value) {
            addCriterion("field_tag like", value, "fieldTag");
            return (Criteria) this;
        }

        public Criteria andFieldTagNotLike(String value) {
            addCriterion("field_tag not like", value, "fieldTag");
            return (Criteria) this;
        }

        public Criteria andFieldTagIn(List<String> values) {
            addCriterion("field_tag in", values, "fieldTag");
            return (Criteria) this;
        }

        public Criteria andFieldTagNotIn(List<String> values) {
            addCriterion("field_tag not in", values, "fieldTag");
            return (Criteria) this;
        }

        public Criteria andFieldTagBetween(String value1, String value2) {
            addCriterion("field_tag between", value1, value2, "fieldTag");
            return (Criteria) this;
        }

        public Criteria andFieldTagNotBetween(String value1, String value2) {
            addCriterion("field_tag not between", value1, value2, "fieldTag");
            return (Criteria) this;
        }

        public Criteria andSqlCriterion(String value) {
            addCriterion("(" + value + ")");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pci_api_parameter_mapping
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}