package com.fit2cloud.itsm.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class PciApiRequestLog implements Serializable {
    @ApiModelProperty("主键索引")
    private String pciApiLogId;

    @ApiModelProperty("请求体信息")
    private String requestBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_api_request_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_request_log.pci_api_log_id
     *
     * @return the value of pci_api_request_log.pci_api_log_id
     *
     * @mbg.generated
     */
    public String getPciApiLogId() {
        return pciApiLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_request_log.pci_api_log_id
     *
     * @param pciApiLogId the value for pci_api_request_log.pci_api_log_id
     *
     * @mbg.generated
     */
    public void setPciApiLogId(String pciApiLogId) {
        this.pciApiLogId = pciApiLogId == null ? null : pciApiLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_request_log.request_body
     *
     * @return the value of pci_api_request_log.request_body
     *
     * @mbg.generated
     */
    public String getRequestBody() {
        return requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_request_log.request_body
     *
     * @param requestBody the value for pci_api_request_log.request_body
     *
     * @mbg.generated
     */
    public void setRequestBody(String requestBody) {
        this.requestBody = requestBody == null ? null : requestBody.trim();
    }
}