package com.fit2cloud.itsm.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class PciApiParameterMappingDictionary implements Serializable {
    @ApiModelProperty("主键索引")
    private String id;

    @ApiModelProperty("api字段映射表ID")
    private String parameterMappingId;

    @ApiModelProperty("源字段值")
    private String sourceFieldValue;

    @ApiModelProperty("映射字段值")
    private String targetFieldValue;

    @ApiModelProperty("默认映射标识")
    private Boolean isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping_dictionary.id
     *
     * @return the value of pci_api_parameter_mapping_dictionary.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping_dictionary.id
     *
     * @param id the value for pci_api_parameter_mapping_dictionary.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping_dictionary.parameter_mapping_id
     *
     * @return the value of pci_api_parameter_mapping_dictionary.parameter_mapping_id
     *
     * @mbg.generated
     */
    public String getParameterMappingId() {
        return parameterMappingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping_dictionary.parameter_mapping_id
     *
     * @param parameterMappingId the value for pci_api_parameter_mapping_dictionary.parameter_mapping_id
     *
     * @mbg.generated
     */
    public void setParameterMappingId(String parameterMappingId) {
        this.parameterMappingId = parameterMappingId == null ? null : parameterMappingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping_dictionary.source_field_value
     *
     * @return the value of pci_api_parameter_mapping_dictionary.source_field_value
     *
     * @mbg.generated
     */
    public String getSourceFieldValue() {
        return sourceFieldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping_dictionary.source_field_value
     *
     * @param sourceFieldValue the value for pci_api_parameter_mapping_dictionary.source_field_value
     *
     * @mbg.generated
     */
    public void setSourceFieldValue(String sourceFieldValue) {
        this.sourceFieldValue = sourceFieldValue == null ? null : sourceFieldValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping_dictionary.target_field_value
     *
     * @return the value of pci_api_parameter_mapping_dictionary.target_field_value
     *
     * @mbg.generated
     */
    public String getTargetFieldValue() {
        return targetFieldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping_dictionary.target_field_value
     *
     * @param targetFieldValue the value for pci_api_parameter_mapping_dictionary.target_field_value
     *
     * @mbg.generated
     */
    public void setTargetFieldValue(String targetFieldValue) {
        this.targetFieldValue = targetFieldValue == null ? null : targetFieldValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_api_parameter_mapping_dictionary.is_default
     *
     * @return the value of pci_api_parameter_mapping_dictionary.is_default
     *
     * @mbg.generated
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_api_parameter_mapping_dictionary.is_default
     *
     * @param isDefault the value for pci_api_parameter_mapping_dictionary.is_default
     *
     * @mbg.generated
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }
}