package com.fit2cloud.itsm.model;

import java.util.ArrayList;
import java.util.List;

public class PciApiParameterMappingDictionaryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    public PciApiParameterMappingDictionaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParameterMappingIdIsNull() {
            addCriterion("parameter_mapping_id is null");
            return (Criteria) this;
        }

        public Criteria andParameterMappingIdIsNotNull() {
            addCriterion("parameter_mapping_id is not null");
            return (Criteria) this;
        }

        public Criteria andParameterMappingIdEqualTo(String value) {
            addCriterion("parameter_mapping_id =", value, "parameterMappingId");
            return (Criteria) this;
        }

        public Criteria andParameterMappingIdNotEqualTo(String value) {
            addCriterion("parameter_mapping_id <>", value, "parameterMappingId");
            return (Criteria) this;
        }

        public Criteria andParameterMappingIdGreaterThan(String value) {
            addCriterion("parameter_mapping_id >", value, "parameterMappingId");
            return (Criteria) this;
        }

        public Criteria andParameterMappingIdGreaterThanOrEqualTo(String value) {
            addCriterion("parameter_mapping_id >=", value, "parameterMappingId");
            return (Criteria) this;
        }

        public Criteria andParameterMappingIdLessThan(String value) {
            addCriterion("parameter_mapping_id <", value, "parameterMappingId");
            return (Criteria) this;
        }

        public Criteria andParameterMappingIdLessThanOrEqualTo(String value) {
            addCriterion("parameter_mapping_id <=", value, "parameterMappingId");
            return (Criteria) this;
        }

        public Criteria andParameterMappingIdLike(String value) {
            addCriterion("parameter_mapping_id like", value, "parameterMappingId");
            return (Criteria) this;
        }

        public Criteria andParameterMappingIdNotLike(String value) {
            addCriterion("parameter_mapping_id not like", value, "parameterMappingId");
            return (Criteria) this;
        }

        public Criteria andParameterMappingIdIn(List<String> values) {
            addCriterion("parameter_mapping_id in", values, "parameterMappingId");
            return (Criteria) this;
        }

        public Criteria andParameterMappingIdNotIn(List<String> values) {
            addCriterion("parameter_mapping_id not in", values, "parameterMappingId");
            return (Criteria) this;
        }

        public Criteria andParameterMappingIdBetween(String value1, String value2) {
            addCriterion("parameter_mapping_id between", value1, value2, "parameterMappingId");
            return (Criteria) this;
        }

        public Criteria andParameterMappingIdNotBetween(String value1, String value2) {
            addCriterion("parameter_mapping_id not between", value1, value2, "parameterMappingId");
            return (Criteria) this;
        }

        public Criteria andSourceFieldValueIsNull() {
            addCriterion("source_field_value is null");
            return (Criteria) this;
        }

        public Criteria andSourceFieldValueIsNotNull() {
            addCriterion("source_field_value is not null");
            return (Criteria) this;
        }

        public Criteria andSourceFieldValueEqualTo(String value) {
            addCriterion("source_field_value =", value, "sourceFieldValue");
            return (Criteria) this;
        }

        public Criteria andSourceFieldValueNotEqualTo(String value) {
            addCriterion("source_field_value <>", value, "sourceFieldValue");
            return (Criteria) this;
        }

        public Criteria andSourceFieldValueGreaterThan(String value) {
            addCriterion("source_field_value >", value, "sourceFieldValue");
            return (Criteria) this;
        }

        public Criteria andSourceFieldValueGreaterThanOrEqualTo(String value) {
            addCriterion("source_field_value >=", value, "sourceFieldValue");
            return (Criteria) this;
        }

        public Criteria andSourceFieldValueLessThan(String value) {
            addCriterion("source_field_value <", value, "sourceFieldValue");
            return (Criteria) this;
        }

        public Criteria andSourceFieldValueLessThanOrEqualTo(String value) {
            addCriterion("source_field_value <=", value, "sourceFieldValue");
            return (Criteria) this;
        }

        public Criteria andSourceFieldValueLike(String value) {
            addCriterion("source_field_value like", value, "sourceFieldValue");
            return (Criteria) this;
        }

        public Criteria andSourceFieldValueNotLike(String value) {
            addCriterion("source_field_value not like", value, "sourceFieldValue");
            return (Criteria) this;
        }

        public Criteria andSourceFieldValueIn(List<String> values) {
            addCriterion("source_field_value in", values, "sourceFieldValue");
            return (Criteria) this;
        }

        public Criteria andSourceFieldValueNotIn(List<String> values) {
            addCriterion("source_field_value not in", values, "sourceFieldValue");
            return (Criteria) this;
        }

        public Criteria andSourceFieldValueBetween(String value1, String value2) {
            addCriterion("source_field_value between", value1, value2, "sourceFieldValue");
            return (Criteria) this;
        }

        public Criteria andSourceFieldValueNotBetween(String value1, String value2) {
            addCriterion("source_field_value not between", value1, value2, "sourceFieldValue");
            return (Criteria) this;
        }

        public Criteria andTargetFieldValueIsNull() {
            addCriterion("target_field_value is null");
            return (Criteria) this;
        }

        public Criteria andTargetFieldValueIsNotNull() {
            addCriterion("target_field_value is not null");
            return (Criteria) this;
        }

        public Criteria andTargetFieldValueEqualTo(String value) {
            addCriterion("target_field_value =", value, "targetFieldValue");
            return (Criteria) this;
        }

        public Criteria andTargetFieldValueNotEqualTo(String value) {
            addCriterion("target_field_value <>", value, "targetFieldValue");
            return (Criteria) this;
        }

        public Criteria andTargetFieldValueGreaterThan(String value) {
            addCriterion("target_field_value >", value, "targetFieldValue");
            return (Criteria) this;
        }

        public Criteria andTargetFieldValueGreaterThanOrEqualTo(String value) {
            addCriterion("target_field_value >=", value, "targetFieldValue");
            return (Criteria) this;
        }

        public Criteria andTargetFieldValueLessThan(String value) {
            addCriterion("target_field_value <", value, "targetFieldValue");
            return (Criteria) this;
        }

        public Criteria andTargetFieldValueLessThanOrEqualTo(String value) {
            addCriterion("target_field_value <=", value, "targetFieldValue");
            return (Criteria) this;
        }

        public Criteria andTargetFieldValueLike(String value) {
            addCriterion("target_field_value like", value, "targetFieldValue");
            return (Criteria) this;
        }

        public Criteria andTargetFieldValueNotLike(String value) {
            addCriterion("target_field_value not like", value, "targetFieldValue");
            return (Criteria) this;
        }

        public Criteria andTargetFieldValueIn(List<String> values) {
            addCriterion("target_field_value in", values, "targetFieldValue");
            return (Criteria) this;
        }

        public Criteria andTargetFieldValueNotIn(List<String> values) {
            addCriterion("target_field_value not in", values, "targetFieldValue");
            return (Criteria) this;
        }

        public Criteria andTargetFieldValueBetween(String value1, String value2) {
            addCriterion("target_field_value between", value1, value2, "targetFieldValue");
            return (Criteria) this;
        }

        public Criteria andTargetFieldValueNotBetween(String value1, String value2) {
            addCriterion("target_field_value not between", value1, value2, "targetFieldValue");
            return (Criteria) this;
        }

        public Criteria andIsDefaultIsNull() {
            addCriterion("is_default is null");
            return (Criteria) this;
        }

        public Criteria andIsDefaultIsNotNull() {
            addCriterion("is_default is not null");
            return (Criteria) this;
        }

        public Criteria andIsDefaultEqualTo(Boolean value) {
            addCriterion("is_default =", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultNotEqualTo(Boolean value) {
            addCriterion("is_default <>", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultGreaterThan(Boolean value) {
            addCriterion("is_default >", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_default >=", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultLessThan(Boolean value) {
            addCriterion("is_default <", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultLessThanOrEqualTo(Boolean value) {
            addCriterion("is_default <=", value, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultIn(List<Boolean> values) {
            addCriterion("is_default in", values, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultNotIn(List<Boolean> values) {
            addCriterion("is_default not in", values, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultBetween(Boolean value1, Boolean value2) {
            addCriterion("is_default between", value1, value2, "isDefault");
            return (Criteria) this;
        }

        public Criteria andIsDefaultNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_default not between", value1, value2, "isDefault");
            return (Criteria) this;
        }

        public Criteria andSqlCriterion(String value) {
            addCriterion("(" + value + ")");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pci_api_parameter_mapping_dictionary
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}