package com.fit2cloud.itsm.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class PciExternalSystemOrgMappingKey implements Serializable {
    @ApiModelProperty("组织 id")
    private String orgId;

    @ApiModelProperty("主编码")
    private String externalSystemOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_external_system_org_mapping
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org_mapping.org_id
     *
     * @return the value of pci_external_system_org_mapping.org_id
     *
     * @mbg.generated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org_mapping.org_id
     *
     * @param orgId the value for pci_external_system_org_mapping.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org_mapping.external_system_org_id
     *
     * @return the value of pci_external_system_org_mapping.external_system_org_id
     *
     * @mbg.generated
     */
    public String getExternalSystemOrgId() {
        return externalSystemOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org_mapping.external_system_org_id
     *
     * @param externalSystemOrgId the value for pci_external_system_org_mapping.external_system_org_id
     *
     * @mbg.generated
     */
    public void setExternalSystemOrgId(String externalSystemOrgId) {
        this.externalSystemOrgId = externalSystemOrgId == null ? null : externalSystemOrgId.trim();
    }
}