package com.fit2cloud.itsm.model;

import java.util.ArrayList;
import java.util.List;

public class PciExternalSystemOrgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    public PciExternalSystemOrgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(String value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(String value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(String value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(String value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(String value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLike(String value) {
            addCriterion("parent_id like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotLike(String value) {
            addCriterion("parent_id not like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<String> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<String> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(String value1, String value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(String value1, String value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andNcOrgIdIsNull() {
            addCriterion("nc_org_id is null");
            return (Criteria) this;
        }

        public Criteria andNcOrgIdIsNotNull() {
            addCriterion("nc_org_id is not null");
            return (Criteria) this;
        }

        public Criteria andNcOrgIdEqualTo(String value) {
            addCriterion("nc_org_id =", value, "ncOrgId");
            return (Criteria) this;
        }

        public Criteria andNcOrgIdNotEqualTo(String value) {
            addCriterion("nc_org_id <>", value, "ncOrgId");
            return (Criteria) this;
        }

        public Criteria andNcOrgIdGreaterThan(String value) {
            addCriterion("nc_org_id >", value, "ncOrgId");
            return (Criteria) this;
        }

        public Criteria andNcOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("nc_org_id >=", value, "ncOrgId");
            return (Criteria) this;
        }

        public Criteria andNcOrgIdLessThan(String value) {
            addCriterion("nc_org_id <", value, "ncOrgId");
            return (Criteria) this;
        }

        public Criteria andNcOrgIdLessThanOrEqualTo(String value) {
            addCriterion("nc_org_id <=", value, "ncOrgId");
            return (Criteria) this;
        }

        public Criteria andNcOrgIdLike(String value) {
            addCriterion("nc_org_id like", value, "ncOrgId");
            return (Criteria) this;
        }

        public Criteria andNcOrgIdNotLike(String value) {
            addCriterion("nc_org_id not like", value, "ncOrgId");
            return (Criteria) this;
        }

        public Criteria andNcOrgIdIn(List<String> values) {
            addCriterion("nc_org_id in", values, "ncOrgId");
            return (Criteria) this;
        }

        public Criteria andNcOrgIdNotIn(List<String> values) {
            addCriterion("nc_org_id not in", values, "ncOrgId");
            return (Criteria) this;
        }

        public Criteria andNcOrgIdBetween(String value1, String value2) {
            addCriterion("nc_org_id between", value1, value2, "ncOrgId");
            return (Criteria) this;
        }

        public Criteria andNcOrgIdNotBetween(String value1, String value2) {
            addCriterion("nc_org_id not between", value1, value2, "ncOrgId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andShortNameIsNull() {
            addCriterion("short_name is null");
            return (Criteria) this;
        }

        public Criteria andShortNameIsNotNull() {
            addCriterion("short_name is not null");
            return (Criteria) this;
        }

        public Criteria andShortNameEqualTo(String value) {
            addCriterion("short_name =", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotEqualTo(String value) {
            addCriterion("short_name <>", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameGreaterThan(String value) {
            addCriterion("short_name >", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("short_name >=", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameLessThan(String value) {
            addCriterion("short_name <", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameLessThanOrEqualTo(String value) {
            addCriterion("short_name <=", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameLike(String value) {
            addCriterion("short_name like", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotLike(String value) {
            addCriterion("short_name not like", value, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameIn(List<String> values) {
            addCriterion("short_name in", values, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotIn(List<String> values) {
            addCriterion("short_name not in", values, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameBetween(String value1, String value2) {
            addCriterion("short_name between", value1, value2, "shortName");
            return (Criteria) this;
        }

        public Criteria andShortNameNotBetween(String value1, String value2) {
            addCriterion("short_name not between", value1, value2, "shortName");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andBusinessCorporationIsNull() {
            addCriterion("business_corporation is null");
            return (Criteria) this;
        }

        public Criteria andBusinessCorporationIsNotNull() {
            addCriterion("business_corporation is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessCorporationEqualTo(String value) {
            addCriterion("business_corporation =", value, "businessCorporation");
            return (Criteria) this;
        }

        public Criteria andBusinessCorporationNotEqualTo(String value) {
            addCriterion("business_corporation <>", value, "businessCorporation");
            return (Criteria) this;
        }

        public Criteria andBusinessCorporationGreaterThan(String value) {
            addCriterion("business_corporation >", value, "businessCorporation");
            return (Criteria) this;
        }

        public Criteria andBusinessCorporationGreaterThanOrEqualTo(String value) {
            addCriterion("business_corporation >=", value, "businessCorporation");
            return (Criteria) this;
        }

        public Criteria andBusinessCorporationLessThan(String value) {
            addCriterion("business_corporation <", value, "businessCorporation");
            return (Criteria) this;
        }

        public Criteria andBusinessCorporationLessThanOrEqualTo(String value) {
            addCriterion("business_corporation <=", value, "businessCorporation");
            return (Criteria) this;
        }

        public Criteria andBusinessCorporationLike(String value) {
            addCriterion("business_corporation like", value, "businessCorporation");
            return (Criteria) this;
        }

        public Criteria andBusinessCorporationNotLike(String value) {
            addCriterion("business_corporation not like", value, "businessCorporation");
            return (Criteria) this;
        }

        public Criteria andBusinessCorporationIn(List<String> values) {
            addCriterion("business_corporation in", values, "businessCorporation");
            return (Criteria) this;
        }

        public Criteria andBusinessCorporationNotIn(List<String> values) {
            addCriterion("business_corporation not in", values, "businessCorporation");
            return (Criteria) this;
        }

        public Criteria andBusinessCorporationBetween(String value1, String value2) {
            addCriterion("business_corporation between", value1, value2, "businessCorporation");
            return (Criteria) this;
        }

        public Criteria andBusinessCorporationNotBetween(String value1, String value2) {
            addCriterion("business_corporation not between", value1, value2, "businessCorporation");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNoIsNull() {
            addCriterion("org_admin_no is null");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNoIsNotNull() {
            addCriterion("org_admin_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNoEqualTo(String value) {
            addCriterion("org_admin_no =", value, "orgAdminNo");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNoNotEqualTo(String value) {
            addCriterion("org_admin_no <>", value, "orgAdminNo");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNoGreaterThan(String value) {
            addCriterion("org_admin_no >", value, "orgAdminNo");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNoGreaterThanOrEqualTo(String value) {
            addCriterion("org_admin_no >=", value, "orgAdminNo");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNoLessThan(String value) {
            addCriterion("org_admin_no <", value, "orgAdminNo");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNoLessThanOrEqualTo(String value) {
            addCriterion("org_admin_no <=", value, "orgAdminNo");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNoLike(String value) {
            addCriterion("org_admin_no like", value, "orgAdminNo");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNoNotLike(String value) {
            addCriterion("org_admin_no not like", value, "orgAdminNo");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNoIn(List<String> values) {
            addCriterion("org_admin_no in", values, "orgAdminNo");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNoNotIn(List<String> values) {
            addCriterion("org_admin_no not in", values, "orgAdminNo");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNoBetween(String value1, String value2) {
            addCriterion("org_admin_no between", value1, value2, "orgAdminNo");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNoNotBetween(String value1, String value2) {
            addCriterion("org_admin_no not between", value1, value2, "orgAdminNo");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNameIsNull() {
            addCriterion("org_admin_name is null");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNameIsNotNull() {
            addCriterion("org_admin_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNameEqualTo(String value) {
            addCriterion("org_admin_name =", value, "orgAdminName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNameNotEqualTo(String value) {
            addCriterion("org_admin_name <>", value, "orgAdminName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNameGreaterThan(String value) {
            addCriterion("org_admin_name >", value, "orgAdminName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNameGreaterThanOrEqualTo(String value) {
            addCriterion("org_admin_name >=", value, "orgAdminName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNameLessThan(String value) {
            addCriterion("org_admin_name <", value, "orgAdminName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNameLessThanOrEqualTo(String value) {
            addCriterion("org_admin_name <=", value, "orgAdminName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNameLike(String value) {
            addCriterion("org_admin_name like", value, "orgAdminName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNameNotLike(String value) {
            addCriterion("org_admin_name not like", value, "orgAdminName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNameIn(List<String> values) {
            addCriterion("org_admin_name in", values, "orgAdminName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNameNotIn(List<String> values) {
            addCriterion("org_admin_name not in", values, "orgAdminName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNameBetween(String value1, String value2) {
            addCriterion("org_admin_name between", value1, value2, "orgAdminName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminNameNotBetween(String value1, String value2) {
            addCriterion("org_admin_name not between", value1, value2, "orgAdminName");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitCodeIsNull() {
            addCriterion("business_unit_code is null");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitCodeIsNotNull() {
            addCriterion("business_unit_code is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitCodeEqualTo(String value) {
            addCriterion("business_unit_code =", value, "businessUnitCode");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitCodeNotEqualTo(String value) {
            addCriterion("business_unit_code <>", value, "businessUnitCode");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitCodeGreaterThan(String value) {
            addCriterion("business_unit_code >", value, "businessUnitCode");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitCodeGreaterThanOrEqualTo(String value) {
            addCriterion("business_unit_code >=", value, "businessUnitCode");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitCodeLessThan(String value) {
            addCriterion("business_unit_code <", value, "businessUnitCode");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitCodeLessThanOrEqualTo(String value) {
            addCriterion("business_unit_code <=", value, "businessUnitCode");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitCodeLike(String value) {
            addCriterion("business_unit_code like", value, "businessUnitCode");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitCodeNotLike(String value) {
            addCriterion("business_unit_code not like", value, "businessUnitCode");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitCodeIn(List<String> values) {
            addCriterion("business_unit_code in", values, "businessUnitCode");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitCodeNotIn(List<String> values) {
            addCriterion("business_unit_code not in", values, "businessUnitCode");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitCodeBetween(String value1, String value2) {
            addCriterion("business_unit_code between", value1, value2, "businessUnitCode");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitCodeNotBetween(String value1, String value2) {
            addCriterion("business_unit_code not between", value1, value2, "businessUnitCode");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostNameIsNull() {
            addCriterion("org_admin_post_name is null");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostNameIsNotNull() {
            addCriterion("org_admin_post_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostNameEqualTo(String value) {
            addCriterion("org_admin_post_name =", value, "orgAdminPostName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostNameNotEqualTo(String value) {
            addCriterion("org_admin_post_name <>", value, "orgAdminPostName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostNameGreaterThan(String value) {
            addCriterion("org_admin_post_name >", value, "orgAdminPostName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostNameGreaterThanOrEqualTo(String value) {
            addCriterion("org_admin_post_name >=", value, "orgAdminPostName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostNameLessThan(String value) {
            addCriterion("org_admin_post_name <", value, "orgAdminPostName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostNameLessThanOrEqualTo(String value) {
            addCriterion("org_admin_post_name <=", value, "orgAdminPostName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostNameLike(String value) {
            addCriterion("org_admin_post_name like", value, "orgAdminPostName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostNameNotLike(String value) {
            addCriterion("org_admin_post_name not like", value, "orgAdminPostName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostNameIn(List<String> values) {
            addCriterion("org_admin_post_name in", values, "orgAdminPostName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostNameNotIn(List<String> values) {
            addCriterion("org_admin_post_name not in", values, "orgAdminPostName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostNameBetween(String value1, String value2) {
            addCriterion("org_admin_post_name between", value1, value2, "orgAdminPostName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostNameNotBetween(String value1, String value2) {
            addCriterion("org_admin_post_name not between", value1, value2, "orgAdminPostName");
            return (Criteria) this;
        }

        public Criteria andNcOrgParentIdIsNull() {
            addCriterion("nc_org_parent_id is null");
            return (Criteria) this;
        }

        public Criteria andNcOrgParentIdIsNotNull() {
            addCriterion("nc_org_parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andNcOrgParentIdEqualTo(String value) {
            addCriterion("nc_org_parent_id =", value, "ncOrgParentId");
            return (Criteria) this;
        }

        public Criteria andNcOrgParentIdNotEqualTo(String value) {
            addCriterion("nc_org_parent_id <>", value, "ncOrgParentId");
            return (Criteria) this;
        }

        public Criteria andNcOrgParentIdGreaterThan(String value) {
            addCriterion("nc_org_parent_id >", value, "ncOrgParentId");
            return (Criteria) this;
        }

        public Criteria andNcOrgParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("nc_org_parent_id >=", value, "ncOrgParentId");
            return (Criteria) this;
        }

        public Criteria andNcOrgParentIdLessThan(String value) {
            addCriterion("nc_org_parent_id <", value, "ncOrgParentId");
            return (Criteria) this;
        }

        public Criteria andNcOrgParentIdLessThanOrEqualTo(String value) {
            addCriterion("nc_org_parent_id <=", value, "ncOrgParentId");
            return (Criteria) this;
        }

        public Criteria andNcOrgParentIdLike(String value) {
            addCriterion("nc_org_parent_id like", value, "ncOrgParentId");
            return (Criteria) this;
        }

        public Criteria andNcOrgParentIdNotLike(String value) {
            addCriterion("nc_org_parent_id not like", value, "ncOrgParentId");
            return (Criteria) this;
        }

        public Criteria andNcOrgParentIdIn(List<String> values) {
            addCriterion("nc_org_parent_id in", values, "ncOrgParentId");
            return (Criteria) this;
        }

        public Criteria andNcOrgParentIdNotIn(List<String> values) {
            addCriterion("nc_org_parent_id not in", values, "ncOrgParentId");
            return (Criteria) this;
        }

        public Criteria andNcOrgParentIdBetween(String value1, String value2) {
            addCriterion("nc_org_parent_id between", value1, value2, "ncOrgParentId");
            return (Criteria) this;
        }

        public Criteria andNcOrgParentIdNotBetween(String value1, String value2) {
            addCriterion("nc_org_parent_id not between", value1, value2, "ncOrgParentId");
            return (Criteria) this;
        }

        public Criteria andParentNameIsNull() {
            addCriterion("parent_name is null");
            return (Criteria) this;
        }

        public Criteria andParentNameIsNotNull() {
            addCriterion("parent_name is not null");
            return (Criteria) this;
        }

        public Criteria andParentNameEqualTo(String value) {
            addCriterion("parent_name =", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameNotEqualTo(String value) {
            addCriterion("parent_name <>", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameGreaterThan(String value) {
            addCriterion("parent_name >", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameGreaterThanOrEqualTo(String value) {
            addCriterion("parent_name >=", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameLessThan(String value) {
            addCriterion("parent_name <", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameLessThanOrEqualTo(String value) {
            addCriterion("parent_name <=", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameLike(String value) {
            addCriterion("parent_name like", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameNotLike(String value) {
            addCriterion("parent_name not like", value, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameIn(List<String> values) {
            addCriterion("parent_name in", values, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameNotIn(List<String> values) {
            addCriterion("parent_name not in", values, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameBetween(String value1, String value2) {
            addCriterion("parent_name between", value1, value2, "parentName");
            return (Criteria) this;
        }

        public Criteria andParentNameNotBetween(String value1, String value2) {
            addCriterion("parent_name not between", value1, value2, "parentName");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostIdIsNull() {
            addCriterion("org_admin_post_id is null");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostIdIsNotNull() {
            addCriterion("org_admin_post_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostIdEqualTo(String value) {
            addCriterion("org_admin_post_id =", value, "orgAdminPostId");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostIdNotEqualTo(String value) {
            addCriterion("org_admin_post_id <>", value, "orgAdminPostId");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostIdGreaterThan(String value) {
            addCriterion("org_admin_post_id >", value, "orgAdminPostId");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostIdGreaterThanOrEqualTo(String value) {
            addCriterion("org_admin_post_id >=", value, "orgAdminPostId");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostIdLessThan(String value) {
            addCriterion("org_admin_post_id <", value, "orgAdminPostId");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostIdLessThanOrEqualTo(String value) {
            addCriterion("org_admin_post_id <=", value, "orgAdminPostId");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostIdLike(String value) {
            addCriterion("org_admin_post_id like", value, "orgAdminPostId");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostIdNotLike(String value) {
            addCriterion("org_admin_post_id not like", value, "orgAdminPostId");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostIdIn(List<String> values) {
            addCriterion("org_admin_post_id in", values, "orgAdminPostId");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostIdNotIn(List<String> values) {
            addCriterion("org_admin_post_id not in", values, "orgAdminPostId");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostIdBetween(String value1, String value2) {
            addCriterion("org_admin_post_id between", value1, value2, "orgAdminPostId");
            return (Criteria) this;
        }

        public Criteria andOrgAdminPostIdNotBetween(String value1, String value2) {
            addCriterion("org_admin_post_id not between", value1, value2, "orgAdminPostId");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitNameIsNull() {
            addCriterion("business_unit_name is null");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitNameIsNotNull() {
            addCriterion("business_unit_name is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitNameEqualTo(String value) {
            addCriterion("business_unit_name =", value, "businessUnitName");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitNameNotEqualTo(String value) {
            addCriterion("business_unit_name <>", value, "businessUnitName");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitNameGreaterThan(String value) {
            addCriterion("business_unit_name >", value, "businessUnitName");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitNameGreaterThanOrEqualTo(String value) {
            addCriterion("business_unit_name >=", value, "businessUnitName");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitNameLessThan(String value) {
            addCriterion("business_unit_name <", value, "businessUnitName");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitNameLessThanOrEqualTo(String value) {
            addCriterion("business_unit_name <=", value, "businessUnitName");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitNameLike(String value) {
            addCriterion("business_unit_name like", value, "businessUnitName");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitNameNotLike(String value) {
            addCriterion("business_unit_name not like", value, "businessUnitName");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitNameIn(List<String> values) {
            addCriterion("business_unit_name in", values, "businessUnitName");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitNameNotIn(List<String> values) {
            addCriterion("business_unit_name not in", values, "businessUnitName");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitNameBetween(String value1, String value2) {
            addCriterion("business_unit_name between", value1, value2, "businessUnitName");
            return (Criteria) this;
        }

        public Criteria andBusinessUnitNameNotBetween(String value1, String value2) {
            addCriterion("business_unit_name not between", value1, value2, "businessUnitName");
            return (Criteria) this;
        }

        public Criteria andRevokedIsNull() {
            addCriterion("revoked is null");
            return (Criteria) this;
        }

        public Criteria andRevokedIsNotNull() {
            addCriterion("revoked is not null");
            return (Criteria) this;
        }

        public Criteria andRevokedEqualTo(String value) {
            addCriterion("revoked =", value, "revoked");
            return (Criteria) this;
        }

        public Criteria andRevokedNotEqualTo(String value) {
            addCriterion("revoked <>", value, "revoked");
            return (Criteria) this;
        }

        public Criteria andRevokedGreaterThan(String value) {
            addCriterion("revoked >", value, "revoked");
            return (Criteria) this;
        }

        public Criteria andRevokedGreaterThanOrEqualTo(String value) {
            addCriterion("revoked >=", value, "revoked");
            return (Criteria) this;
        }

        public Criteria andRevokedLessThan(String value) {
            addCriterion("revoked <", value, "revoked");
            return (Criteria) this;
        }

        public Criteria andRevokedLessThanOrEqualTo(String value) {
            addCriterion("revoked <=", value, "revoked");
            return (Criteria) this;
        }

        public Criteria andRevokedLike(String value) {
            addCriterion("revoked like", value, "revoked");
            return (Criteria) this;
        }

        public Criteria andRevokedNotLike(String value) {
            addCriterion("revoked not like", value, "revoked");
            return (Criteria) this;
        }

        public Criteria andRevokedIn(List<String> values) {
            addCriterion("revoked in", values, "revoked");
            return (Criteria) this;
        }

        public Criteria andRevokedNotIn(List<String> values) {
            addCriterion("revoked not in", values, "revoked");
            return (Criteria) this;
        }

        public Criteria andRevokedBetween(String value1, String value2) {
            addCriterion("revoked between", value1, value2, "revoked");
            return (Criteria) this;
        }

        public Criteria andRevokedNotBetween(String value1, String value2) {
            addCriterion("revoked not between", value1, value2, "revoked");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeIsNull() {
            addCriterion("company_code is null");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeIsNotNull() {
            addCriterion("company_code is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeEqualTo(String value) {
            addCriterion("company_code =", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotEqualTo(String value) {
            addCriterion("company_code <>", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeGreaterThan(String value) {
            addCriterion("company_code >", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("company_code >=", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeLessThan(String value) {
            addCriterion("company_code <", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeLessThanOrEqualTo(String value) {
            addCriterion("company_code <=", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeLike(String value) {
            addCriterion("company_code like", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotLike(String value) {
            addCriterion("company_code not like", value, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeIn(List<String> values) {
            addCriterion("company_code in", values, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotIn(List<String> values) {
            addCriterion("company_code not in", values, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeBetween(String value1, String value2) {
            addCriterion("company_code between", value1, value2, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCodeNotBetween(String value1, String value2) {
            addCriterion("company_code not between", value1, value2, "companyCode");
            return (Criteria) this;
        }

        public Criteria andCompanyCdescriptionIsNull() {
            addCriterion("company_cdescription is null");
            return (Criteria) this;
        }

        public Criteria andCompanyCdescriptionIsNotNull() {
            addCriterion("company_cdescription is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyCdescriptionEqualTo(String value) {
            addCriterion("company_cdescription =", value, "companyCdescription");
            return (Criteria) this;
        }

        public Criteria andCompanyCdescriptionNotEqualTo(String value) {
            addCriterion("company_cdescription <>", value, "companyCdescription");
            return (Criteria) this;
        }

        public Criteria andCompanyCdescriptionGreaterThan(String value) {
            addCriterion("company_cdescription >", value, "companyCdescription");
            return (Criteria) this;
        }

        public Criteria andCompanyCdescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("company_cdescription >=", value, "companyCdescription");
            return (Criteria) this;
        }

        public Criteria andCompanyCdescriptionLessThan(String value) {
            addCriterion("company_cdescription <", value, "companyCdescription");
            return (Criteria) this;
        }

        public Criteria andCompanyCdescriptionLessThanOrEqualTo(String value) {
            addCriterion("company_cdescription <=", value, "companyCdescription");
            return (Criteria) this;
        }

        public Criteria andCompanyCdescriptionLike(String value) {
            addCriterion("company_cdescription like", value, "companyCdescription");
            return (Criteria) this;
        }

        public Criteria andCompanyCdescriptionNotLike(String value) {
            addCriterion("company_cdescription not like", value, "companyCdescription");
            return (Criteria) this;
        }

        public Criteria andCompanyCdescriptionIn(List<String> values) {
            addCriterion("company_cdescription in", values, "companyCdescription");
            return (Criteria) this;
        }

        public Criteria andCompanyCdescriptionNotIn(List<String> values) {
            addCriterion("company_cdescription not in", values, "companyCdescription");
            return (Criteria) this;
        }

        public Criteria andCompanyCdescriptionBetween(String value1, String value2) {
            addCriterion("company_cdescription between", value1, value2, "companyCdescription");
            return (Criteria) this;
        }

        public Criteria andCompanyCdescriptionNotBetween(String value1, String value2) {
            addCriterion("company_cdescription not between", value1, value2, "companyCdescription");
            return (Criteria) this;
        }

        public Criteria andSqlCriterion(String value) {
            addCriterion("(" + value + ")");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pci_external_system_org
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}