package com.fit2cloud.itsm.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class PciExternalSystemUser implements Serializable {
    @ApiModelProperty("主编码")
    private String id;

    @ApiModelProperty("员工工号")
    private String workNo;

    @ApiModelProperty("姓名")
    private String name;

    @ApiModelProperty("岗位序列编码")
    private String positionSerialCode;

    @ApiModelProperty("性别")
    private String sex;

    @ApiModelProperty("所属公司编码")
    private String companyCode;

    @ApiModelProperty("所属公司名称")
    private String companyName;

    @ApiModelProperty("经营单位编码")
    private String businessUnitCode;

    @ApiModelProperty("所属部门编码")
    private String orgId;

    @ApiModelProperty("所属部门名称")
    private String orgName;

    @ApiModelProperty("证件号码")
    private String idcardNo;

    @ApiModelProperty("手机")
    private String phoneNumber;

    @ApiModelProperty("电子邮箱")
    private String email;

    @ApiModelProperty("岗位编码")
    private String positionCode;

    @ApiModelProperty("岗位名称")
    private String positionName;

    @ApiModelProperty("岗位序列")
    private String positionSerial;

    @ApiModelProperty("是否在岗")
    private String onTheJob;

    @ApiModelProperty("员工类别编码")
    private String typeCode;

    @ApiModelProperty("员工类别")
    private String type;

    @ApiModelProperty("经营单位名称")
    private String businessUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_external_system_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.id
     *
     * @return the value of pci_external_system_user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.id
     *
     * @param id the value for pci_external_system_user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.work_no
     *
     * @return the value of pci_external_system_user.work_no
     *
     * @mbg.generated
     */
    public String getWorkNo() {
        return workNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.work_no
     *
     * @param workNo the value for pci_external_system_user.work_no
     *
     * @mbg.generated
     */
    public void setWorkNo(String workNo) {
        this.workNo = workNo == null ? null : workNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.name
     *
     * @return the value of pci_external_system_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.name
     *
     * @param name the value for pci_external_system_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.position_serial_code
     *
     * @return the value of pci_external_system_user.position_serial_code
     *
     * @mbg.generated
     */
    public String getPositionSerialCode() {
        return positionSerialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.position_serial_code
     *
     * @param positionSerialCode the value for pci_external_system_user.position_serial_code
     *
     * @mbg.generated
     */
    public void setPositionSerialCode(String positionSerialCode) {
        this.positionSerialCode = positionSerialCode == null ? null : positionSerialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.sex
     *
     * @return the value of pci_external_system_user.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.sex
     *
     * @param sex the value for pci_external_system_user.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.company_code
     *
     * @return the value of pci_external_system_user.company_code
     *
     * @mbg.generated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.company_code
     *
     * @param companyCode the value for pci_external_system_user.company_code
     *
     * @mbg.generated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.company_name
     *
     * @return the value of pci_external_system_user.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.company_name
     *
     * @param companyName the value for pci_external_system_user.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.business_unit_code
     *
     * @return the value of pci_external_system_user.business_unit_code
     *
     * @mbg.generated
     */
    public String getBusinessUnitCode() {
        return businessUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.business_unit_code
     *
     * @param businessUnitCode the value for pci_external_system_user.business_unit_code
     *
     * @mbg.generated
     */
    public void setBusinessUnitCode(String businessUnitCode) {
        this.businessUnitCode = businessUnitCode == null ? null : businessUnitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.org_id
     *
     * @return the value of pci_external_system_user.org_id
     *
     * @mbg.generated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.org_id
     *
     * @param orgId the value for pci_external_system_user.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.org_name
     *
     * @return the value of pci_external_system_user.org_name
     *
     * @mbg.generated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.org_name
     *
     * @param orgName the value for pci_external_system_user.org_name
     *
     * @mbg.generated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.idcard_no
     *
     * @return the value of pci_external_system_user.idcard_no
     *
     * @mbg.generated
     */
    public String getIdcardNo() {
        return idcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.idcard_no
     *
     * @param idcardNo the value for pci_external_system_user.idcard_no
     *
     * @mbg.generated
     */
    public void setIdcardNo(String idcardNo) {
        this.idcardNo = idcardNo == null ? null : idcardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.phone_number
     *
     * @return the value of pci_external_system_user.phone_number
     *
     * @mbg.generated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.phone_number
     *
     * @param phoneNumber the value for pci_external_system_user.phone_number
     *
     * @mbg.generated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.email
     *
     * @return the value of pci_external_system_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.email
     *
     * @param email the value for pci_external_system_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.position_code
     *
     * @return the value of pci_external_system_user.position_code
     *
     * @mbg.generated
     */
    public String getPositionCode() {
        return positionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.position_code
     *
     * @param positionCode the value for pci_external_system_user.position_code
     *
     * @mbg.generated
     */
    public void setPositionCode(String positionCode) {
        this.positionCode = positionCode == null ? null : positionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.position_name
     *
     * @return the value of pci_external_system_user.position_name
     *
     * @mbg.generated
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.position_name
     *
     * @param positionName the value for pci_external_system_user.position_name
     *
     * @mbg.generated
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.position_serial
     *
     * @return the value of pci_external_system_user.position_serial
     *
     * @mbg.generated
     */
    public String getPositionSerial() {
        return positionSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.position_serial
     *
     * @param positionSerial the value for pci_external_system_user.position_serial
     *
     * @mbg.generated
     */
    public void setPositionSerial(String positionSerial) {
        this.positionSerial = positionSerial == null ? null : positionSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.on_the_job
     *
     * @return the value of pci_external_system_user.on_the_job
     *
     * @mbg.generated
     */
    public String getOnTheJob() {
        return onTheJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.on_the_job
     *
     * @param onTheJob the value for pci_external_system_user.on_the_job
     *
     * @mbg.generated
     */
    public void setOnTheJob(String onTheJob) {
        this.onTheJob = onTheJob == null ? null : onTheJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.type_code
     *
     * @return the value of pci_external_system_user.type_code
     *
     * @mbg.generated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.type_code
     *
     * @param typeCode the value for pci_external_system_user.type_code
     *
     * @mbg.generated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.type
     *
     * @return the value of pci_external_system_user.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.type
     *
     * @param type the value for pci_external_system_user.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_user.business_unit_name
     *
     * @return the value of pci_external_system_user.business_unit_name
     *
     * @mbg.generated
     */
    public String getBusinessUnitName() {
        return businessUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_user.business_unit_name
     *
     * @param businessUnitName the value for pci_external_system_user.business_unit_name
     *
     * @mbg.generated
     */
    public void setBusinessUnitName(String businessUnitName) {
        this.businessUnitName = businessUnitName == null ? null : businessUnitName.trim();
    }
}