package com.fit2cloud.itsm.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class PciExternalSystemOrg implements Serializable {
    @ApiModelProperty("主编码")
    private String id;

    @ApiModelProperty("父节点编码")
    private String parentId;

    @ApiModelProperty("NC组织编码")
    private String ncOrgId;

    @ApiModelProperty("组织名称")
    private String name;

    @ApiModelProperty("简称")
    private String shortName;

    @ApiModelProperty("组织类型：dept（部门）/corp(公司)")
    private String type;

    @ApiModelProperty("企业法人")
    private String businessCorporation;

    @ApiModelProperty("部门负责人工号")
    private String orgAdminNo;

    @ApiModelProperty("部门负责人姓名")
    private String orgAdminName;

    @ApiModelProperty("经营单位编码")
    private String businessUnitCode;

    @ApiModelProperty("部门负责人岗位名称")
    private String orgAdminPostName;

    @ApiModelProperty("NC上级组织编码")
    private String ncOrgParentId;

    @ApiModelProperty("上级组织名称")
    private String parentName;

    @ApiModelProperty("部门负责人岗位编码")
    private String orgAdminPostId;

    @ApiModelProperty("经营单位名称")
    private String businessUnitName;

    @ApiModelProperty("是否撤销")
    private String revoked;

    @ApiModelProperty("公司编码")
    private String companyCode;

    @ApiModelProperty("公司描述")
    private String companyCdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_external_system_org
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.id
     *
     * @return the value of pci_external_system_org.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.id
     *
     * @param id the value for pci_external_system_org.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.parent_id
     *
     * @return the value of pci_external_system_org.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.parent_id
     *
     * @param parentId the value for pci_external_system_org.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.nc_org_id
     *
     * @return the value of pci_external_system_org.nc_org_id
     *
     * @mbg.generated
     */
    public String getNcOrgId() {
        return ncOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.nc_org_id
     *
     * @param ncOrgId the value for pci_external_system_org.nc_org_id
     *
     * @mbg.generated
     */
    public void setNcOrgId(String ncOrgId) {
        this.ncOrgId = ncOrgId == null ? null : ncOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.name
     *
     * @return the value of pci_external_system_org.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.name
     *
     * @param name the value for pci_external_system_org.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.short_name
     *
     * @return the value of pci_external_system_org.short_name
     *
     * @mbg.generated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.short_name
     *
     * @param shortName the value for pci_external_system_org.short_name
     *
     * @mbg.generated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.type
     *
     * @return the value of pci_external_system_org.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.type
     *
     * @param type the value for pci_external_system_org.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.business_corporation
     *
     * @return the value of pci_external_system_org.business_corporation
     *
     * @mbg.generated
     */
    public String getBusinessCorporation() {
        return businessCorporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.business_corporation
     *
     * @param businessCorporation the value for pci_external_system_org.business_corporation
     *
     * @mbg.generated
     */
    public void setBusinessCorporation(String businessCorporation) {
        this.businessCorporation = businessCorporation == null ? null : businessCorporation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.org_admin_no
     *
     * @return the value of pci_external_system_org.org_admin_no
     *
     * @mbg.generated
     */
    public String getOrgAdminNo() {
        return orgAdminNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.org_admin_no
     *
     * @param orgAdminNo the value for pci_external_system_org.org_admin_no
     *
     * @mbg.generated
     */
    public void setOrgAdminNo(String orgAdminNo) {
        this.orgAdminNo = orgAdminNo == null ? null : orgAdminNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.org_admin_name
     *
     * @return the value of pci_external_system_org.org_admin_name
     *
     * @mbg.generated
     */
    public String getOrgAdminName() {
        return orgAdminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.org_admin_name
     *
     * @param orgAdminName the value for pci_external_system_org.org_admin_name
     *
     * @mbg.generated
     */
    public void setOrgAdminName(String orgAdminName) {
        this.orgAdminName = orgAdminName == null ? null : orgAdminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.business_unit_code
     *
     * @return the value of pci_external_system_org.business_unit_code
     *
     * @mbg.generated
     */
    public String getBusinessUnitCode() {
        return businessUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.business_unit_code
     *
     * @param businessUnitCode the value for pci_external_system_org.business_unit_code
     *
     * @mbg.generated
     */
    public void setBusinessUnitCode(String businessUnitCode) {
        this.businessUnitCode = businessUnitCode == null ? null : businessUnitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.org_admin_post_name
     *
     * @return the value of pci_external_system_org.org_admin_post_name
     *
     * @mbg.generated
     */
    public String getOrgAdminPostName() {
        return orgAdminPostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.org_admin_post_name
     *
     * @param orgAdminPostName the value for pci_external_system_org.org_admin_post_name
     *
     * @mbg.generated
     */
    public void setOrgAdminPostName(String orgAdminPostName) {
        this.orgAdminPostName = orgAdminPostName == null ? null : orgAdminPostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.nc_org_parent_id
     *
     * @return the value of pci_external_system_org.nc_org_parent_id
     *
     * @mbg.generated
     */
    public String getNcOrgParentId() {
        return ncOrgParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.nc_org_parent_id
     *
     * @param ncOrgParentId the value for pci_external_system_org.nc_org_parent_id
     *
     * @mbg.generated
     */
    public void setNcOrgParentId(String ncOrgParentId) {
        this.ncOrgParentId = ncOrgParentId == null ? null : ncOrgParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.parent_name
     *
     * @return the value of pci_external_system_org.parent_name
     *
     * @mbg.generated
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.parent_name
     *
     * @param parentName the value for pci_external_system_org.parent_name
     *
     * @mbg.generated
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.org_admin_post_id
     *
     * @return the value of pci_external_system_org.org_admin_post_id
     *
     * @mbg.generated
     */
    public String getOrgAdminPostId() {
        return orgAdminPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.org_admin_post_id
     *
     * @param orgAdminPostId the value for pci_external_system_org.org_admin_post_id
     *
     * @mbg.generated
     */
    public void setOrgAdminPostId(String orgAdminPostId) {
        this.orgAdminPostId = orgAdminPostId == null ? null : orgAdminPostId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.business_unit_name
     *
     * @return the value of pci_external_system_org.business_unit_name
     *
     * @mbg.generated
     */
    public String getBusinessUnitName() {
        return businessUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.business_unit_name
     *
     * @param businessUnitName the value for pci_external_system_org.business_unit_name
     *
     * @mbg.generated
     */
    public void setBusinessUnitName(String businessUnitName) {
        this.businessUnitName = businessUnitName == null ? null : businessUnitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.revoked
     *
     * @return the value of pci_external_system_org.revoked
     *
     * @mbg.generated
     */
    public String getRevoked() {
        return revoked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.revoked
     *
     * @param revoked the value for pci_external_system_org.revoked
     *
     * @mbg.generated
     */
    public void setRevoked(String revoked) {
        this.revoked = revoked == null ? null : revoked.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.company_code
     *
     * @return the value of pci_external_system_org.company_code
     *
     * @mbg.generated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.company_code
     *
     * @param companyCode the value for pci_external_system_org.company_code
     *
     * @mbg.generated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_org.company_cdescription
     *
     * @return the value of pci_external_system_org.company_cdescription
     *
     * @mbg.generated
     */
    public String getCompanyCdescription() {
        return companyCdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_org.company_cdescription
     *
     * @param companyCdescription the value for pci_external_system_org.company_cdescription
     *
     * @mbg.generated
     */
    public void setCompanyCdescription(String companyCdescription) {
        this.companyCdescription = companyCdescription == null ? null : companyCdescription.trim();
    }
}