package com.fit2cloud.itsm.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class PciExternalSystemSyncDetailLog implements Serializable {
    @ApiModelProperty("")
    private String id;

    @ApiModelProperty("日志主表ID")
    private String pciApiLogId;

    @ApiModelProperty("同步机构或用户的主编码")
    private String soaId;

    @ApiModelProperty("机构名称或用户名称")
    private String name;

    @ApiModelProperty("类型：机构/用户")
    private Boolean type;

    @ApiModelProperty("创建时间")
    private Long createTime;

    @ApiModelProperty("同步异常信息")
    private String errMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_external_system_sync_detail_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_sync_detail_log.id
     *
     * @return the value of pci_external_system_sync_detail_log.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_sync_detail_log.id
     *
     * @param id the value for pci_external_system_sync_detail_log.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_sync_detail_log.pci_api_log_id
     *
     * @return the value of pci_external_system_sync_detail_log.pci_api_log_id
     *
     * @mbg.generated
     */
    public String getPciApiLogId() {
        return pciApiLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_sync_detail_log.pci_api_log_id
     *
     * @param pciApiLogId the value for pci_external_system_sync_detail_log.pci_api_log_id
     *
     * @mbg.generated
     */
    public void setPciApiLogId(String pciApiLogId) {
        this.pciApiLogId = pciApiLogId == null ? null : pciApiLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_sync_detail_log.soa_id
     *
     * @return the value of pci_external_system_sync_detail_log.soa_id
     *
     * @mbg.generated
     */
    public String getSoaId() {
        return soaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_sync_detail_log.soa_id
     *
     * @param soaId the value for pci_external_system_sync_detail_log.soa_id
     *
     * @mbg.generated
     */
    public void setSoaId(String soaId) {
        this.soaId = soaId == null ? null : soaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_sync_detail_log.name
     *
     * @return the value of pci_external_system_sync_detail_log.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_sync_detail_log.name
     *
     * @param name the value for pci_external_system_sync_detail_log.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_sync_detail_log.type
     *
     * @return the value of pci_external_system_sync_detail_log.type
     *
     * @mbg.generated
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_sync_detail_log.type
     *
     * @param type the value for pci_external_system_sync_detail_log.type
     *
     * @mbg.generated
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_sync_detail_log.create_time
     *
     * @return the value of pci_external_system_sync_detail_log.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_sync_detail_log.create_time
     *
     * @param createTime the value for pci_external_system_sync_detail_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_external_system_sync_detail_log.err_msg
     *
     * @return the value of pci_external_system_sync_detail_log.err_msg
     *
     * @mbg.generated
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_external_system_sync_detail_log.err_msg
     *
     * @param errMsg the value for pci_external_system_sync_detail_log.err_msg
     *
     * @mbg.generated
     */
    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg == null ? null : errMsg.trim();
    }
}