package com.fit2cloud.itsm.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class PciProcess implements Serializable {
    @ApiModelProperty("")
    private String processId;

    @ApiModelProperty("")
    private String module;

    @ApiModelProperty("")
    private String businessKey;

    @ApiModelProperty("")
    private String resourceType;

    @ApiModelProperty("")
    private String externalProcessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_process
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_process.process_id
     *
     * @return the value of pci_process.process_id
     *
     * @mbg.generated
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_process.process_id
     *
     * @param processId the value for pci_process.process_id
     *
     * @mbg.generated
     */
    public void setProcessId(String processId) {
        this.processId = processId == null ? null : processId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_process.module
     *
     * @return the value of pci_process.module
     *
     * @mbg.generated
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_process.module
     *
     * @param module the value for pci_process.module
     *
     * @mbg.generated
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_process.business_key
     *
     * @return the value of pci_process.business_key
     *
     * @mbg.generated
     */
    public String getBusinessKey() {
        return businessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_process.business_key
     *
     * @param businessKey the value for pci_process.business_key
     *
     * @mbg.generated
     */
    public void setBusinessKey(String businessKey) {
        this.businessKey = businessKey == null ? null : businessKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_process.resource_type
     *
     * @return the value of pci_process.resource_type
     *
     * @mbg.generated
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_process.resource_type
     *
     * @param resourceType the value for pci_process.resource_type
     *
     * @mbg.generated
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_process.external_process_id
     *
     * @return the value of pci_process.external_process_id
     *
     * @mbg.generated
     */
    public String getExternalProcessId() {
        return externalProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_process.external_process_id
     *
     * @param externalProcessId the value for pci_process.external_process_id
     *
     * @mbg.generated
     */
    public void setExternalProcessId(String externalProcessId) {
        this.externalProcessId = externalProcessId == null ? null : externalProcessId.trim();
    }
}