package com.fit2cloud.itsm.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class PciSyncUserSetting implements Serializable {
    @ApiModelProperty("")
    private String id;

    @ApiModelProperty("同步用户ID")
    private String syncUserId;

    @ApiModelProperty("同步用户名称")
    private String syncUserName;

    @ApiModelProperty("同步用户编码")
    private String syncUserCode;

    @ApiModelProperty("同步用户描述")
    private String remark;

    @ApiModelProperty("同步标识（1同步/0不同步）")
    private Boolean isSync;

    @ApiModelProperty("创建时间")
    private Long createTime;

    @ApiModelProperty("最后更新时间")
    private Long updateTime;

    @ApiModelProperty("")
    private String createUser;

    @ApiModelProperty("")
    private String updateUser;

    @ApiModelProperty("邮箱")
    private String email;

    @ApiModelProperty("用户所属机构ID")
    private String orgId;

    @ApiModelProperty("用户所属机构名称")
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_sync_user_setting
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_user_setting.id
     *
     * @return the value of pci_sync_user_setting.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_user_setting.id
     *
     * @param id the value for pci_sync_user_setting.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_user_setting.sync_user_id
     *
     * @return the value of pci_sync_user_setting.sync_user_id
     *
     * @mbg.generated
     */
    public String getSyncUserId() {
        return syncUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_user_setting.sync_user_id
     *
     * @param syncUserId the value for pci_sync_user_setting.sync_user_id
     *
     * @mbg.generated
     */
    public void setSyncUserId(String syncUserId) {
        this.syncUserId = syncUserId == null ? null : syncUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_user_setting.sync_user_name
     *
     * @return the value of pci_sync_user_setting.sync_user_name
     *
     * @mbg.generated
     */
    public String getSyncUserName() {
        return syncUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_user_setting.sync_user_name
     *
     * @param syncUserName the value for pci_sync_user_setting.sync_user_name
     *
     * @mbg.generated
     */
    public void setSyncUserName(String syncUserName) {
        this.syncUserName = syncUserName == null ? null : syncUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_user_setting.sync_user_code
     *
     * @return the value of pci_sync_user_setting.sync_user_code
     *
     * @mbg.generated
     */
    public String getSyncUserCode() {
        return syncUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_user_setting.sync_user_code
     *
     * @param syncUserCode the value for pci_sync_user_setting.sync_user_code
     *
     * @mbg.generated
     */
    public void setSyncUserCode(String syncUserCode) {
        this.syncUserCode = syncUserCode == null ? null : syncUserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_user_setting.remark
     *
     * @return the value of pci_sync_user_setting.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_user_setting.remark
     *
     * @param remark the value for pci_sync_user_setting.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_user_setting.is_sync
     *
     * @return the value of pci_sync_user_setting.is_sync
     *
     * @mbg.generated
     */
    public Boolean getIsSync() {
        return isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_user_setting.is_sync
     *
     * @param isSync the value for pci_sync_user_setting.is_sync
     *
     * @mbg.generated
     */
    public void setIsSync(Boolean isSync) {
        this.isSync = isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_user_setting.create_time
     *
     * @return the value of pci_sync_user_setting.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_user_setting.create_time
     *
     * @param createTime the value for pci_sync_user_setting.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_user_setting.update_time
     *
     * @return the value of pci_sync_user_setting.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_user_setting.update_time
     *
     * @param updateTime the value for pci_sync_user_setting.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_user_setting.create_user
     *
     * @return the value of pci_sync_user_setting.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_user_setting.create_user
     *
     * @param createUser the value for pci_sync_user_setting.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_user_setting.update_user
     *
     * @return the value of pci_sync_user_setting.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_user_setting.update_user
     *
     * @param updateUser the value for pci_sync_user_setting.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_user_setting.email
     *
     * @return the value of pci_sync_user_setting.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_user_setting.email
     *
     * @param email the value for pci_sync_user_setting.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_user_setting.org_id
     *
     * @return the value of pci_sync_user_setting.org_id
     *
     * @mbg.generated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_user_setting.org_id
     *
     * @param orgId the value for pci_sync_user_setting.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_user_setting.org_name
     *
     * @return the value of pci_sync_user_setting.org_name
     *
     * @mbg.generated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_user_setting.org_name
     *
     * @param orgName the value for pci_sync_user_setting.org_name
     *
     * @mbg.generated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }
}