package com.fit2cloud.itsm.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class PciSyncOrgSetting implements Serializable {
    @ApiModelProperty("")
    private String id;

    @ApiModelProperty("同步机构ID")
    private String syncOrgId;

    @ApiModelProperty("同步机构名称")
    private String syncOrgName;

    @ApiModelProperty("同步机构编码")
    private String syncOrgCode;

    @ApiModelProperty("同步机构描述")
    private String remark;

    @ApiModelProperty("同步标识（1同步/0不同步）")
    private Boolean isSync;

    @ApiModelProperty("创建时间")
    private Long createTime;

    @ApiModelProperty("最后更新时间")
    private Long updateTime;

    @ApiModelProperty("")
    private String createUser;

    @ApiModelProperty("")
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pci_sync_org_setting
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_org_setting.id
     *
     * @return the value of pci_sync_org_setting.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_org_setting.id
     *
     * @param id the value for pci_sync_org_setting.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_org_setting.sync_org_id
     *
     * @return the value of pci_sync_org_setting.sync_org_id
     *
     * @mbg.generated
     */
    public String getSyncOrgId() {
        return syncOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_org_setting.sync_org_id
     *
     * @param syncOrgId the value for pci_sync_org_setting.sync_org_id
     *
     * @mbg.generated
     */
    public void setSyncOrgId(String syncOrgId) {
        this.syncOrgId = syncOrgId == null ? null : syncOrgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_org_setting.sync_org_name
     *
     * @return the value of pci_sync_org_setting.sync_org_name
     *
     * @mbg.generated
     */
    public String getSyncOrgName() {
        return syncOrgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_org_setting.sync_org_name
     *
     * @param syncOrgName the value for pci_sync_org_setting.sync_org_name
     *
     * @mbg.generated
     */
    public void setSyncOrgName(String syncOrgName) {
        this.syncOrgName = syncOrgName == null ? null : syncOrgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_org_setting.sync_org_code
     *
     * @return the value of pci_sync_org_setting.sync_org_code
     *
     * @mbg.generated
     */
    public String getSyncOrgCode() {
        return syncOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_org_setting.sync_org_code
     *
     * @param syncOrgCode the value for pci_sync_org_setting.sync_org_code
     *
     * @mbg.generated
     */
    public void setSyncOrgCode(String syncOrgCode) {
        this.syncOrgCode = syncOrgCode == null ? null : syncOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_org_setting.remark
     *
     * @return the value of pci_sync_org_setting.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_org_setting.remark
     *
     * @param remark the value for pci_sync_org_setting.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_org_setting.is_sync
     *
     * @return the value of pci_sync_org_setting.is_sync
     *
     * @mbg.generated
     */
    public Boolean getIsSync() {
        return isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_org_setting.is_sync
     *
     * @param isSync the value for pci_sync_org_setting.is_sync
     *
     * @mbg.generated
     */
    public void setIsSync(Boolean isSync) {
        this.isSync = isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_org_setting.create_time
     *
     * @return the value of pci_sync_org_setting.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_org_setting.create_time
     *
     * @param createTime the value for pci_sync_org_setting.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_org_setting.update_time
     *
     * @return the value of pci_sync_org_setting.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_org_setting.update_time
     *
     * @param updateTime the value for pci_sync_org_setting.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_org_setting.create_user
     *
     * @return the value of pci_sync_org_setting.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_org_setting.create_user
     *
     * @param createUser the value for pci_sync_org_setting.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pci_sync_org_setting.update_user
     *
     * @return the value of pci_sync_org_setting.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pci_sync_org_setting.update_user
     *
     * @param updateUser the value for pci_sync_org_setting.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}